version: '3'

services:
  rafs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8080:8080"

  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    image: osdu-rafsddms_tests
    restart: "no"
    volumes:
      - ./tests/:/tests
      - ./client/:/client
    entrypoint: [ "bash", "-c"]
    command: ["python -m pytest -p no:cacheprovider --ignore=integration"]

  integration:
    image: osdu-rafsddms_tests
    restart: "no"
    volumes:
      - ./tests/:/tests
      - ./client/:/client
    working_dir: /
    entrypoint: [ "bash", "-c",
      "pytest -n auto ./tests/integration/tests --ddms-base-url \"${DDMS_BASE_URL}\" --url-prefix \"${URL_PREFIX}\" --partition \"${PARTITION}\" --bearer-token \"${ACCESS_TOKEN}\""]
    profiles: ["tests"]
    depends_on:
      - rafs
      - tests
