version: '3'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    # Env file can be setup here or in command line docker-compose --env-file <>
    env_file:
      - .env
    volumes:
      - ./app/:/app/app
    entrypoint: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload

  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    image: osdu-rafsddms_tests
    restart: "no"
    volumes:
      - ./tests/:/tests
      - ./client/:/client
    entrypoint: [ "bash", "-c"]
    command: ["python -m pytest -p no:cacheprovider --ignore=integration"]

  integration:
    image: osdu-rafsddms_tests
    restart: "no"
    volumes:
      - ./tests/:/tests
      - ./client/:/client
    working_dir: /
    entrypoint: [ "bash", "-c",
      "pytest -n auto ./tests/integration/tests --ddms-base-url \"${DDMS_BASE_URL}\" --url-prefix \"${URL_PREFIX}\" --partition \"${PARTITION}\" --bearer-token \"${ACCESS_TOKEN}\""]
    profiles: ["integration"]
    depends_on:
      - app
      - tests

  distroless:
    build:
      context: .
      dockerfile: Dockerfile.distroless
    env_file:
      - .env
    profiles: ["distroless"]
    ports:
      - "8088:8088"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8088", "--loop", "uvloop"]
