version: '3.8'

services:
  rafs:
    user: "0:0"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        commit_branch: "Local"
        commit_message: "Local Development"
        release_version: "0.0.0-local"
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./app/:/app/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--workers", "1", "--reload"]
    depends_on:
      - redis

  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    image: osdu-rafsddms_tests
    restart: "no"
    volumes:
      - ./app:/app
      - ./setup.cfg:/setup.cfg
      - ./tests/:/tests
      - ./client/:/client
    entrypoint: [ "bash", "-c"]
    profiles: ["tests"]
    command: ["python -m pytest -p no:cacheprovider --ignore=integration"]

  integration:
    image: osdu-rafsddms_tests
    restart: "no"
    env_file:
      - .env
    volumes:
      - ./tests/:/tests
      - ./client/:/client
    working_dir: /
    entrypoint: [ "bash", "-c",
      "time pytest -n 1 --cov=app --cov-report=term ./tests/integration/tests --ddms-base-url \"${DDMS_BASE_URL}\" --url-prefix \"${URL_PREFIX}\" --partition \"${PARTITION}\" --bearer-token \"${ACCESS_TOKEN}\" --cloud-provider \"${CLOUD_PROVIDER}\""]
    profiles: ["tests"]
    depends_on:
      - rafs
      - tests

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    command: ["redis-stack-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./local_redis.conf:/usr/local/etc/redis/redis.conf
