ARG python_version=3.11
FROM python:${python_version}-bookworm

COPY requirements.txt /app/requirements.txt
RUN pip install --upgrade pip \
      && pip install --no-cache-dir -r /app/requirements.txt

ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH=./

COPY requirements-tests.in ./
COPY requirements.in ./
RUN pip install --upgrade pip && pip install pip-tools && \
      pip-compile requirements.in requirements-tests.in -o requirements-tests.txt -v && \
      pip install -r requirements-tests.txt

COPY ./app /app
COPY ./tests /tests
COPY ./client /client

WORKDIR ./tests

CMD pytest -n auto ./tests/integration/tests --ddms-base-url ${DDMS_BASE_URL} --url-prefix {URL_PREFIX} --partition {PARTITION} --bearer-token ${ACCESS_TOKEN}
