#  Copyright 2023 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  /api/schema-service/v1/schema/osdu:wks:master-data--RockSample:1.0.0
#   timestamp: 2023-02-10T14:53:56+00:00

from __future__ import annotations

from datetime import date
from typing import Optional

from pydantic import BaseModel, Field, constr


class Field0(BaseModel):
    StorageFacilityID: Optional[
        constr(regex=r'^[\w\-\.]+:master-data\-\-StorageFacility:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(None, description='Identifies the warehouse in which the item is stored.')
    StorageLocationDescription: Optional[str] = Field(
        None,
        description='The name of the location where the item is stored. It can be stored in more than one location over time.',
    )
    SampleIdentifier: Optional[str] = Field(
        None,
        description='The item (sample, tape)  identifier, for example a barcode, which identifies the item in the StorageFacility.',
    )
    TerminationDateTime: Optional[date] = Field(
        None,
        description="The date and time at which the item is  no longer stored in the given location.  If the item is still in this storage, the 'TerminationDateTime' is left absent.",
    )
    EffectiveDateTime: Optional[date] = Field(
        None, description='The date the item arrived at the storage location.'
    )
    StorageOrganisationID: Optional[
        constr(regex=r'^[\w\-\.]+:master-data\-\-Organisation:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(
        None, description='Identifies the organisation with which the item is stored.'
    )
