#  Copyright 2023 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  api/schema-service/v1/schema/osdu:wks:master-data--GenericFacility:1.0.0
#   timestamp: 2023-12-12T16:50:26+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field, constr


class Field0(BaseModel):
    FacilityOperatorID: Optional[str] = Field(
        None,
        description="Internal, unique identifier for an item 'AbstractFacilityOperator'. This identifier is used by 'AbstractFacility.CurrentOperatorID' and 'AbstractFacility.InitialOperatorID'.",
        title="Facility Operator ID",
    )
    EffectiveDateTime: Optional[datetime] = Field(
        None,
        description="The date and time at which the facility operator becomes effective.",
    )
    FacilityOperatorOrganisationID: Optional[
        constr(regex=r"^[\w\-\.]+:master-data\-\-Organisation:[\w\-\.\:\%]+:[0-9]*$")
    ] = Field(
        None,
        description="The company that currently operates, or previously operated the facility",
    )
    TerminationDateTime: Optional[datetime] = Field(
        None,
        description="The date and time at which the facility operator is no longer in effect. If the operator is still effective, the 'TerminationDateTime' is left absent.",
    )
    Remark: Optional[str] = Field(
        None, description="A comment or remark about the facility operator."
    )
