{{- template "common.serviceaccount" (list . "os-rafs-ddms.serviceaccount") -}}
{{- define "os-rafs-ddms.serviceaccount" -}}
## Define overrides for the service's service account resource here
{{- end -}}