#  Copyright 2023 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  /api/schema-service/v1/schema/osdu:wks:work-product-component--MultiStageSeparatorTest:1.0.0
#   timestamp: 2023-04-11T05:01:11+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field, constr


class Field0(BaseModel):
    FieldID: Optional[
        constr(regex=r'^[\w\-\.]+:master-data\-\-Field:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(None, description='Reference to Field.')
    GeoTypeID: str = Field(
        'Field',
        const=True,
        description="The fixed type 'Field' for this AbstractGeoFieldContext.",
    )
