apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.conf.appName | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ .Values.conf.appName | quote }}
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  selector:
    app: {{ .Values.conf.appName | quote }}
