#  Copyright 2023 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  /api/schema-service/v1/schema/osdu:wks:master-data--Coring:1.0.0
#   timestamp: 2023-02-08T19:36:11+00:00

from __future__ import annotations

from datetime import date, datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Extra, Field, constr

from .osdu_wks_AbstractAccessControlList_1 import field_0 as field_0_2
from .osdu_wks_AbstractCommonResources_1.field_0 import Field0
from .osdu_wks_AbstractFacilityVerticalMeasurement_1 import field_0
from .osdu_wks_AbstractLegalParentList_1 import field_0 as field_0_1
from .osdu_wks_AbstractLegalTags_1 import field_0 as field_0_4
from .osdu_wks_AbstractMaster_1.field_1 import Field0 as Field0_1
from .osdu_wks_AbstractMetaItem_1 import field_0 as field_0_3
from .osdu_wks_AbstractProjectActivity_1.field_0 import Field0 as Field0_2


class CoreRemark(BaseModel):
    RemarkSource: Optional[str] = Field(
        None,
        description='The person, vendor, interpreter or other provider of information.',
        title='Remark Source',
    )
    RemarkID: Optional[str] = Field(
        None,
        description='A unique identifier for each remark record.',
        title='Remark ID',
    )
    Remark: Optional[str] = Field(
        None, description='A descriptive comment for this remark.', title='Remark'
    )


class Data(Field0, Field0_1, Field0_2):
    BottomDepth: Optional[float] = Field(
        None,
        description="The depth of the base of the core. The reference and kind of depth (e.g. driller's depth versus logger's depth) is described in data.VerticalMeasurement. For SidewallCores this is the depth of the deepest core.",
        title='Bottom Depth',
    )
    CoreDiameter: Optional[float] = Field(
        None, description='The diameter of the core.', title='Core Diameter'
    )
    CoreIdentifier: Optional[str] = Field(
        None,
        description='Native identifier from a Master Data Management System or other trusted source external to OSDU - stored here in order to allow for multi-system connection and synchronization. If used, the "Source" property should identify that source system. i.e. this item is optional.',
        example='421112222200-Core1',
        title='Core Identifier',
    )
    WellboreID: Optional[
        constr(regex=r'^[\w\-\.]+:master-data\-\-Wellbore:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(
        None,
        description='The relationship to the wellbore.',
        example='namespace:master-data--Wellbore:421112222200:',
        title='Wellbore ID',
    )
    PreservationTypeID: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-CorePreservationType:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None,
        description='The kind of preservation applied to this conventional coring or sidewall core.',
        title='Preservation Type ID',
    )
    ServiceCompanyID: Optional[
        constr(regex=r'^[\w\-\.]+:master-data\-\-Organisation:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(
        None,
        description='The coring company that extracted the well core. For Example: ACME Limited PLC',
        example='namespace:master-data--Organisation:ACME-Limited-PLC:',
        title='Service Company ID',
    )
    IsOriented: Optional[bool] = Field(
        None,
        description='Indicates if the core was oriented.',
        title='Core Oriented Indicator',
    )
    TopDepth: Optional[float] = Field(
        None,
        description="The depth of the top of the core. The reference and kind of depth (e.g. driller's depth versus logger's depth) is described in data.VerticalMeasurement. For SidewallCores this is the depth of the shallowest core.",
        title='Top Depth',
    )
    Name: Optional[str] = Field(
        None,
        description='The name of the core. For example ACME 1 Core 1',
        example='ACME 1 Core 1',
        title='Name',
    )
    CoringOperationDate: Optional[date] = Field(
        None, description='The date of the coring operation.', title='Recovery Date'
    )
    HasTrippingSchedule: Optional[bool] = Field(
        None,
        description='Flag indicating whether a detailed tripping schedule is available. Available tripping schedules are usually a sign of controlled coring sample quality.',
        example=True,
    )
    RunNumber: Optional[int] = Field(
        None, description='The coring run number.', title='Run Number'
    )
    CoreNumber: Optional[str] = Field(
        None, description='The vendor assigned core number.', title='Core Number'
    )
    CoreRecoveredDate: Optional[date] = Field(
        None,
        description='The date the core returned to surface.',
        title='Core Recovered Date',
    )
    VerticalMeasurement: Optional[field_0.Field0] = Field(
        None,
        description='References an entry in the VerticalMeasurements array for the Wellbore identified by WellboreID, or a standalone vertical reference which defines the vertical reference datum for all measured depths of the Coring record.',
        example={
            'VerticalReferenceID': 'ZDP',
            'VerticalMeasurementSourceID': 'namespace:reference-data--VerticalMeasurementSource:DRL:',
            'VerticalMeasurementPathID': 'namespace:reference-data--VerticalMeasurementPath:MD:',
            'VerticalMeasurement': 0,
            'VerticalMeasurementDescription': 'Same vertical reference as wellbore ZDP, Measured Depth, Drillers Depth.',
        },
        title='Vertical Measurement',
    )
    CoreRemarks: Optional[List[CoreRemark]] = Field(
        None,
        description='An array contains narrative remarks pertaining to a core.',
        title='Core Remarks',
    )
    PreferredDepthShiftsID: Optional[
        constr(
            regex=r'^[\w\-\.]+:work-product-component\-\-WellLog:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None,
        description='The WellLog representation carrying the preferred core-depth to logging-depth correction or mapping.',
        title='Preferred Depth Shifts ID',
    )
    ExtensionProperties: Optional[Dict[str, Any]] = None


class Coring(BaseModel):
    class Config:
        extra = Extra.forbid

    ancestry: Optional[field_0_1.Field0] = Field(
        None,
        description='The links to data, which constitute the inputs, from which this record instance is derived.',
        title='Ancestry',
    )
    data: Optional[Data] = None
    kind: constr(regex=r'^[\w\-\.]+:[\w\-\.]+:[\w\-\.]+:[0-9]+.[0-9]+.[0-9]+$') = Field(
        ...,
        description='The schema identification for the OSDU resource object following the pattern {Namespace}:{Source}:{Type}:{VersionMajor}.{VersionMinor}.{VersionPatch}. The versioning scheme follows the semantic versioning, https://semver.org/.',
        example='osdu:wks:master-data--Coring:1.0.0',
        title='Entity Kind',
    )
    acl: field_0_2.Field0 = Field(
        ...,
        description='The access control tags associated with this entity.',
        title='Access Control List',
    )
    version: Optional[int] = Field(
        None,
        description='The version number of this OSDU resource; set by the framework.',
        example=1562066009929332,
        title='Version Number',
    )
    tags: Optional[Dict[str, str]] = Field(
        None,
        description='A generic dictionary of string keys mapping to string value. Only strings are permitted as keys and values.',
        example={'NameOfKey': 'String value'},
        title='Tag Dictionary',
    )
    modifyUser: Optional[str] = Field(
        None,
        description='The user reference, which created this version of this resource object. Set by the System.',
        example='some-user@some-company-cloud.com',
        title='Resource Object Version Creation User Reference',
    )
    modifyTime: Optional[datetime] = Field(
        None,
        description='Timestamp of the time at which this version of the OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.',
        example='2020-12-16T11:52:24.477Z',
        title='Resource Object Version Creation DateTime',
    )
    createTime: Optional[datetime] = Field(
        None,
        description='Timestamp of the time at which initial version of this OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.',
        example='2020-12-16T11:46:20.163Z',
        title='Resource Object Creation DateTime',
    )
    meta: Optional[List[field_0_3.Field0]] = Field(
        None,
        description='The Frame of Reference meta data section linking the named properties to self-contained definitions.',
        title='Frame of Reference Meta Data',
    )
    legal: field_0_4.Field0 = Field(
        ...,
        description="The entity's legal tags and compliance status. The actual contents associated with the legal tags is managed by the Compliance Service.",
        title='Legal Tags',
    )
    createUser: Optional[str] = Field(
        None,
        description='The user reference, which created the first version of this resource object. Set by the System.',
        example='some-user@some-company-cloud.com',
        title='Resource Object Creation User Reference',
    )
    id: Optional[
        constr(regex=r'^[\w\-\.]+:master-data\-\-Coring:[\w\-\.\:\%]+$')
    ] = Field(
        None,
        description='Previously called ResourceID or SRN which identifies this OSDU resource object without version.',
        example='namespace:master-data--Coring:22300d5b-9a54-5a4b-a40a-0d242a064894',
        title='Entity ID',
    )
