#  Copyright 2023 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  api/schema-service/v1/schema/osdu:wks:master-data--SampleContainer:1.0.0
#   timestamp: 2023-12-12T16:51:26+00:00

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Extra, Field, constr

from .osdu_wks_AbstractAccessControlList_1 import field_0 as field_0_3
from .osdu_wks_AbstractCommonResources_1.field_0 import Field0
from .osdu_wks_AbstractLegalParentList_1 import field_0 as field_0_2
from .osdu_wks_AbstractLegalTags_1 import field_0 as field_0_5
from .osdu_wks_AbstractMaster_1.field_2 import Field0 as Field0_1
from .osdu_wks_AbstractMetaItem_1 import field_0 as field_0_4
from .osdu_wks_AbstractPTCondition_1 import field_0
from .osdu_wks_AbstractRemark_1 import field_0 as field_0_1


class ContainerCertification(BaseModel):
    InspectionDate: Optional[datetime] = Field(
        None,
        description="This is the date of the last inspection performed on the sample container.\nReference: \nInspectionDate=PRODML:2.1:FluidSampleContainer.Model.LastInspectionDate",
        title="Inspection Date",
    )
    ValidityPeriod: Optional[float] = Field(
        None,
        description="This is the period or amount of time for which the last inspection or certification process is valid.",
        example="3 years",
        title="Validity Period",
    )
    IsTransportable: Optional[bool] = Field(
        None,
        description="Indicator to determine if the sample container can be transported.",
        title="Is Transportable",
    )
    TransportCertificateDocumentID: Optional[
        constr(
            regex=r"^[\w\-\.]+:work-product-component\-\-Document:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="This is the OSDU object identifier for the file or document containing detailed information on the certification process performed ascertaining its viability for safe transportation of the sample.",
        title="Transport Certificate Document ID",
    )
    NextInspectionDate: Optional[datetime] = Field(
        None,
        description="This is the proposed date for the next inspection to be performed on the sample container.",
        title="Next Inspection Date",
    )


class Data(Field0, Field0_1):
    OperatingConditionRating: field_0.Field0 = Field(
        ...,
        description="This provides the recommended operating conditions (Pressure and Temperature) rating for the sample container.",
        example={"Temperature": 100, "Pressure": 200},
        title="Operating Condition Rating",
    )
    ManufacturerID: Optional[
        constr(regex=r"^[\w\-\.]+:master-data\-\-Organisation:[\w\-\.\:\%]+:[0-9]*$")
    ] = Field(
        None,
        description="The make or manufacturer of the sample container.",
        example="namespace:master-data--Organisation:7dd54874-46de-5ec1-a358-5a0d8abf5242:",
        title="Manufacturer ID",
    )
    SampleContainerServiceTypeIDs: List[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-SampleContainerServiceType:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        ...,
        description="The list of substances, certified by the manufacturer, that the sample container can hold.",
        title="Sample Container Service Type IDs",
    )
    MaterialConstruction: Optional[str] = Field(
        None,
        description="Material used in constructing the sample container.",
        example="Stainless Steel, Aluminium Alloy, Glass.",
        title="Material Construction",
    )
    SampleContainerTypeID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-SampleContainerType:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="The type or kind of the sample container used.",
        example="namespace:reference-data--SampleContainerType:PressurizedPressureCompensatedSample:",
        title="Container Type ID",
    )
    Name: Optional[str] = Field(
        None, description="The name of the container.", title="Name"
    )
    StartDate: Optional[datetime] = Field(
        None,
        description="The date the sample container was commisioned and put in service.",
        example="2023-01-01T12:00:00Z",
        title="Start Date",
    )
    SerialNumber: Optional[str] = Field(
        None,
        description="Unique identifier given by manufacturer for the sample container.",
        example="SN102334555",
        title="Serial Number",
    )
    ContainerIdentifier: str = Field(
        ...,
        description="This refers to an alternate identifier for the sample container available in a system of record external to the OSDU platform and managed by the organization.",
        example="BTL-12345",
        title="Container Identifier",
    )
    OwnerID: Optional[
        constr(regex=r"^[\w\-\.]+:master-data\-\-Organisation:[\w\-\.\:\%]+:[0-9]*$")
    ] = Field(
        None,
        description="The OSDU Record ID for the organization obtained from a reference list.",
        example="namespace:master-data--Organisation:7dd54874-46de-5ec1-a358-5a0d8abf5242:",
        title="Owner ID",
    )
    ExpirationDate: Optional[datetime] = Field(
        None,
        description="The date the sample container reached end of life and should be taken out of commission.",
        title="Expiration Date",
    )
    Capacity: float = Field(
        ...,
        description="Volume of the sample container.",
        example=200,
        title="Capacity",
    )
    Remarks: Optional[field_0_1.Field0] = Field(
        None,
        description="Remarks or comments about this sample container.",
        title="Remarks",
    )
    Model: Optional[str] = Field(
        None,
        description="The model of the sample container as defined by the manufacturer.",
        example="PS100",
        title="Model",
    )
    ContainerCertifications: Optional[List[ContainerCertification]] = Field(
        None,
        description="List of certifications performed on the sample container over time.",
        example=[
            {
                "InspectionDate": "2020-02-13T09:13:15.55Z",
                "ValidityPeriod": 24,
                "IsTransportable": True,
                "TransportCertificateDocumentID": "namespace:work-product-component--Document:0e6a8fdb-0a0a-56db-955a-c62204c42cb0:",
                "NextInspectionDate": "2021-02-13T09:13:15.55Z",
            },
            {
                "InspectionDate": "2021-02-13T09:13:15.55Z",
                "ValidityPeriod": 24,
                "IsTransportable": True,
                "TransportCertificateDocumentID": "namespace:work-product-component--Document:0e6a8fdb-0a0a-56db-955a-c62204c42cb0:",
                "NextInspectionDate": "2022-02-13T09:13:15.55Z",
            },
        ],
        title="Container Certifications",
    )
    ExtensionProperties: Optional[Dict[str, Any]] = None


class SampleContainer(BaseModel):
    class Config:
        extra = Extra.forbid

    ancestry: Optional[field_0_2.Field0] = Field(
        None,
        description="The links to data, which constitute the inputs, from which this record instance is derived.",
        title="Ancestry",
    )
    data: Optional[Data] = None
    kind: constr(regex=r"^[\w\-\.]+:[\w\-\.]+:[\w\-\.]+:[0-9]+.[0-9]+.[0-9]+$") = Field(
        ...,
        description="The schema identification for the OSDU resource object following the pattern {Namespace}:{Source}:{Type}:{VersionMajor}.{VersionMinor}.{VersionPatch}. The versioning scheme follows the semantic versioning, https://semver.org/.",
        example="osdu:wks:master-data--SampleContainer:1.0.0",
        title="Entity Kind",
    )
    acl: field_0_3.Field0 = Field(
        ...,
        description="The access control tags associated with this entity.",
        title="Access Control List",
    )
    version: Optional[int] = Field(
        None,
        description="The version number of this OSDU resource; set by the framework.",
        example=1562066009929332,
        title="Version Number",
    )
    tags: Optional[Dict[str, str]] = Field(
        None,
        description="A generic dictionary of string keys mapping to string value. Only strings are permitted as keys and values.",
        example={"NameOfKey": "String value"},
        title="Tag Dictionary",
    )
    modifyUser: Optional[str] = Field(
        None,
        description="The user reference, which created this version of this resource object. Set by the System.",
        example="some-user@some-company-cloud.com",
        title="Resource Object Version Creation User Reference",
    )
    modifyTime: Optional[datetime] = Field(
        None,
        description="Timestamp of the time at which this version of the OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.",
        example="2020-12-16T11:52:24.477Z",
        title="Resource Object Version Creation DateTime",
    )
    createTime: Optional[datetime] = Field(
        None,
        description="Timestamp of the time at which initial version of this OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.",
        example="2020-12-16T11:46:20.163Z",
        title="Resource Object Creation DateTime",
    )
    meta: Optional[List[field_0_4.Field0]] = Field(
        None,
        description="The Frame of Reference meta data section linking the named properties to self-contained definitions.",
        title="Frame of Reference Meta Data",
    )
    legal: field_0_5.Field0 = Field(
        ...,
        description="The entity's legal tags and compliance status. The actual contents associated with the legal tags is managed by the Compliance Service.",
        title="Legal Tags",
    )
    createUser: Optional[str] = Field(
        None,
        description="The user reference, which created the first version of this resource object. Set by the System.",
        example="some-user@some-company-cloud.com",
        title="Resource Object Creation User Reference",
    )
    id: Optional[
        constr(regex=r"^[\w\-\.]+:master-data\-\-SampleContainer:[\w\-\.\:\%]+$")
    ] = Field(
        None,
        description="Previously called ResourceID or SRN which identifies this OSDU resource object without version.",
        example="namespace:master-data--SampleContainer:22bc1d42-94e7-52d4-9e12-66098d84ebab",
        title="Entity ID",
    )
