#  Copyright 2023 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  /api/schema-service/v1/schema/osdu:wks:work-product-component--SamplesAnalysesReport:1.0.0
#   timestamp: 2023-10-19T16:20:54+00:00

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Extra, Field, constr

from .osdu_wks_AbstractAccessControlList_1 import field_0 as field_0_2
from .osdu_wks_AbstractCommonResources_1.field_0 import Field0
from .osdu_wks_AbstractLegalParentList_1 import field_0 as field_0_1
from .osdu_wks_AbstractLegalTags_1 import field_0 as field_0_4
from .osdu_wks_AbstractMetaItem_1 import field_0 as field_0_3
from .osdu_wks_AbstractRemark_1 import field_0
from .osdu_wks_AbstractWorkProductComponent_1.field_1 import Field0 as Field0_2
from .osdu_wks_AbstractWPCGroupType_1.field_2 import Field0 as Field0_1


class Data(Field0, Field0_1, Field0_2):
    class Config:
        extra = Extra.forbid
        validate_all = True

    LaboratoryIDs: Optional[
        List[
            constr(
                regex=r"^[\w\-\.]+:master-data\-\-Organisation:[\w\-\.\:\%]+:[0-9]*$"
            )
        ]
    ] = Field(
        None,
        description="OSDU Record IDs for the laboratories used to conduct the sample analyses contained in this report. This could represent the laboratory company or the laboratory branch.",
        title="Laboratory ID",
    )
    SampleIDs: Optional[
        List[constr(regex=r"^[\w\-\.]+:master-data\-\-Sample:[\w\-\.\:\%]+:[0-9]*$")]
    ] = Field(
        None,
        description="OSDU Record IDs for the Rock and/or Fluid Sample or Samples on which this batch or batches of analysis were performed.",
        example=[
            "namespace:master-data--Sample:Kentish-Knock-South-1_KK-16:",
            "namespace:master-data--Sample:Kentish-Knock-South-1_KK-17:",
            "namespace:master-data--Sample:Kentish-Knock-South-1_KK-21:",
        ],
    )
    DocumentSubject: Optional[str] = Field(
        None,
        description="A description text or an array of subjects covered by the document. If present this information must compliment the Tag and SubTitle",
    )
    NumberOfPages: Optional[int] = Field(
        None,
        description="Number of pages in the document, useful in cases where if it was described in the acquired manifest as opposed to a derived/calculated value",
    )
    DocumentTypeID: Optional[
        constr(regex=r"^[\w\-\.]+:reference-data\-\-DocumentType:[\w\-\.\:\%]+:[0-9]*$")
    ] = Field(
        None,
        description="The kind of document--from a business standpoint, e.g., multi-well study, etc.",
    )
    DatePublished: Optional[datetime] = Field(
        None,
        description="The date and time that the results of the analysis containing observed measurements or calculations was published",
    )
    LaboratoryNames: Optional[List[str]] = Field(
        None,
        description="List of names of laboratories used to conduct the sample analyses contained in this report. This attribute is more freeform than Laboratory IDs and does not have relationships to OSDU Record IDs. This attribute exists to help with a low bar of ingestion but best practice is to resolve each of these to an OSDU Record ID in the LaboratoryIDs attribute.",
    )
    Remarks: Optional[List[field_0.Field0]] = Field(
        None,
        description="An array containing operational or quality comments pertaining to the sample analysis represented by this work product component.",
    )
    DocumentLanguage: Optional[str] = Field(
        None,
        description="Document language as listed in the ISO 639-3 https://en.wikipedia.org/wiki/ISO_639, https://en.wikipedia.org/wiki/List_of_ISO_639-3_codes",
        example="eng",
    )
    ReportSampleIdentifiers: Optional[List[str]] = Field(
        None,
        description="The names or identifiers of the analyzed samples in this report or document. These names or identifiers are often assigned by the laboratory. This list can be used to assist in locating the appropriate OSDU Sample records or to find the dataset in the parent report.",
        example=["KK-16", "KK-17", "KK-21"],
    )
    SamplesAnalysisCategoryTagIDs: Optional[
        List[
            constr(
                regex=r"^[\w\-\.]+:reference-data\-\-SamplesAnalysisCategoryTag:[\w\-\.\:\%]+:[0-9]*$"
            )
        ]
    ] = Field(
        None,
        description="List of higher level grouping terms that are often used within organisations to search for analysis types in addition to the formal Family and Method properties, but which are variable across organisations and therefore do not need to be governed strictly by the OSDU Forum. For example: SCAL, Static SCAL, Dynamic SCAL, Source Rock Analysis. We suggest you use a namespace, like the operators name, like �Shell.SCAL�. BP.SCAL, Equinor.SCAL, Chevron.SCAL, Exxon.SCAL.....",
        example=[
            "namespace:reference-data--SamplesAnalysisCategoryTag:ExxonMobil-SCAL:"
        ],
    )
    SubTitle: Optional[str] = Field(None, description="The sub-title of the document.")
    DateModified: Optional[datetime] = Field(
        None, description="The date and time that the document was last modified"
    )
    SampleAnalysisTypeIDs: Optional[
        List[
            constr(
                regex=r"^[\w\-\.]+:reference-data\-\-SampleAnalysisType:[\w\-\.\:\%]+:[0-9]*$"
            )
        ]
    ] = Field(
        None,
        description="A list of all sample analysis types represented by this report, whether the sample analysis type relates to Rock, Fluid, or both.",
        example=[
            "namespace:reference-data--SampleAnalysisType:Wettability.Amott-Harvey:"
        ],
    )
    ExtensionProperties: Optional[Dict[str, Any]] = None


class SamplesAnalysesReport(BaseModel):
    class Config:
        extra = Extra.forbid

    ancestry: Optional[field_0_1.Field0] = Field(
        None,
        description="The links to data, which constitute the inputs, from which this record instance is derived.",
        title="Ancestry",
    )
    data: Optional[Data] = None
    kind: constr(regex=r"^[\w\-\.]+:[\w\-\.]+:[\w\-\.]+:[0-9]+.[0-9]+.[0-9]+$") = Field(
        ...,
        description="The schema identification for the OSDU resource object following the pattern {Namespace}:{Source}:{Type}:{VersionMajor}.{VersionMinor}.{VersionPatch}. The versioning scheme follows the semantic versioning, https://semver.org/.",
        example="osdu:wks:work-product-component--SamplesAnalysesReport:1.0.0",
        title="Entity Kind",
    )
    acl: field_0_2.Field0 = Field(
        ...,
        description="The access control tags associated with this entity.",
        title="Access Control List",
    )
    version: Optional[int] = Field(
        None,
        description="The version number of this OSDU resource; set by the framework.",
        example=1562066009929332,
        title="Version Number",
    )
    tags: Optional[Dict[str, str]] = Field(
        None,
        description="A generic dictionary of string keys mapping to string value. Only strings are permitted as keys and values.",
        example={"NameOfKey": "String value"},
        title="Tag Dictionary",
    )
    modifyUser: Optional[str] = Field(
        None,
        description="The user reference, which created this version of this resource object. Set by the System.",
        example="some-user@some-company-cloud.com",
        title="Resource Object Version Creation User Reference",
    )
    modifyTime: Optional[datetime] = Field(
        None,
        description="Timestamp of the time at which this version of the OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.",
        example="2020-12-16T11:52:24.477Z",
        title="Resource Object Version Creation DateTime",
    )
    createTime: Optional[datetime] = Field(
        None,
        description="Timestamp of the time at which initial version of this OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.",
        example="2020-12-16T11:46:20.163Z",
        title="Resource Object Creation DateTime",
    )
    meta: Optional[List[field_0_3.Field0]] = Field(
        None,
        description="The Frame of Reference meta data section linking the named properties to self-contained definitions.",
        title="Frame of Reference Meta Data",
    )
    legal: field_0_4.Field0 = Field(
        ...,
        description="The entity's legal tags and compliance status. The actual contents associated with the legal tags is managed by the Compliance Service.",
        title="Legal Tags",
    )
    createUser: Optional[str] = Field(
        None,
        description="The user reference, which created the first version of this resource object. Set by the System.",
        example="some-user@some-company-cloud.com",
        title="Resource Object Creation User Reference",
    )
    id: Optional[
        constr(
            regex=r"^[\w\-\.]+:work-product-component\-\-SamplesAnalysesReport:[\w\-\.\:\%]+$"
        )
    ] = Field(
        None,
        description="Previously called ResourceID or SRN which identifies this OSDU resource object without version.",
        example="namespace:work-product-component--SamplesAnalysesReport:b632082e-e5aa-5d92-96f5-e5e87c10780c",
        title="Entity ID",
    )
