#  Copyright 2023 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  /api/schema-service/v1/schema/rafsddms:wks:work-product-component--SlimTubeTest:1.0.0
#   timestamp: 2023-05-15T15:35:12+00:00

from __future__ import annotations

from datetime import date, datetime
from typing import Dict, List, Optional

from pydantic import BaseModel, Extra, Field, constr

from .osdu_wks_AbstractAccessControlList_1 import field_0 as field_0_1
from .osdu_wks_AbstractLegalParentList_1 import field_0
from .osdu_wks_AbstractLegalTags_1 import field_0 as field_0_3
from .osdu_wks_AbstractMetaItem_1 import field_0 as field_0_2
from .osdu_wks_AbstractWorkProductComponent_1.field_0 import Field0


class Remark(BaseModel):
    RemarkSource: Optional[str] = Field(
        None,
        description='The person, vendor, interpreter or other provider of information.',
        title='Remark Source',
    )
    RemarkID: Optional[str] = Field(
        None,
        description='A unique identifier for each remark record.',
        title='Remark ID',
    )
    Remark: Optional[str] = Field(
        None, description='A descriptive comment for this remark.', title='Remark'
    )


class Data(Field0):
    PVTReportID: constr(regex=r'^[\w\-\.]+:work-product-component\-\-PVT:[\w\-\.\:\%]+:[0-9]*$') = Field(
        ...,
        description='Unique PVT identifier linked to this Slim Tube Test.',
        title='PVT Report ID',
    )
    LaboratoryName: Optional[str] = Field(
        None,
        description='Name or branch of the laboratory performing the analysis.',
        title='Laboratory Name',
    )
    DDMSDataset: Optional[str] = Field(
        None,
        description='URI link to the measurements which were carried out within this CCE',
        example='https://<vhostname>.<osdu-instance-fqdn>/api/rafs ddms/v1/SlimTUbeTest/get_SlimTubeTest_data_record_id/45',
    )
    AnalysisDate: Optional[date] = Field(
        None,
        description='The date the Slim Tube Test was performed.',
        title='Analysis Date',
    )
    Remarks: Optional[List[Remark]] = Field(
        None,
        description='An array containing operational or quality comments pertaining to a Slim Tube Test.',
        title='Analysis Remarks',
    )
    LabSampleIdentifier: Optional[str] = Field(
        None,
        description='The name or sample identifier assigned to the sample by the laboratory. This name or identifier is used to key into the associated content (e.g., document) to find the portion of the content dealing with the specific sample.',
        example='KK-16',
        title='Laboratory Sample Identifier',
    )
    FluidSampleID: Optional[
        constr(regex=r'^[\w\-\.]+:master-data\-\-FluidSample:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(
        None,
        description='Unique ID of the fluid which was analyzed by Slim Tube Test.',
        title='Fluid Sample ID',
    )


class SlimTubeTest(BaseModel):
    class Config:
        extra = Extra.forbid

    ancestry: Optional[field_0.Field0] = Field(
        None,
        description='The links to data, which constitute the inputs, from which this record instance is derived.',
        title='Ancestry',
    )
    data: Optional[Data] = None
    kind: constr(regex=r'^[\w\-\.]+:[\w\-\.]+:[\w\-\.]+:[0-9]+.[0-9]+.[0-9]+$') = Field(
        ...,
        description='The schema identification for the OSDU resource object following the pattern {Namespace}:{Source}:{Type}:{VersionMajor}.{VersionMinor}.{VersionPatch}. The versioning scheme follows the semantic versioning, https://semver.org/.',
        example='osdu:wks:work-product-component--SlimTUbeTest:1.1.0',
        title='Entity Kind',
    )
    acl: field_0_1.Field0 = Field(
        ...,
        description='The access control tags associated with this entity.',
        title='Access Control List',
    )
    version: Optional[int] = Field(
        None,
        description='The version number of this OSDU resource; set by the framework.',
        example=1562066009929332,
        title='Version Number',
    )
    tags: Optional[Dict[str, str]] = Field(
        None,
        description='A generic dictionary of string keys mapping to string value. Only strings are permitted as keys and values.',
        example={'NameOfKey': 'String value'},
        title='Tag Dictionary',
    )
    modifyUser: Optional[str] = Field(
        None,
        description='The user reference, which created this version of this resource object. Set by the System.',
        example='some-user@some-company-cloud.com',
        title='Resource Object Version Creation User Reference',
    )
    modifyTime: Optional[datetime] = Field(
        None,
        description='Timestamp of the time at which this version of the OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.',
        example='2020-12-16T11:52:24.477Z',
        title='Resource Object Version Creation DateTime',
    )
    createTime: Optional[datetime] = Field(
        None,
        description='Timestamp of the time at which initial version of this OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.',
        example='2020-12-16T11:46:20.163Z',
        title='Resource Object Creation DateTime',
    )
    meta: Optional[List[field_0_2.Field0]] = Field(
        None,
        description='The Frame of Reference meta data section linking the named properties to self-contained definitions.',
        title='Frame of Reference Meta Data',
    )
    legal: field_0_3.Field0 = Field(
        ...,
        description="The entity's legal tags and compliance status. The actual contents associated with the legal tags is managed by the Compliance Service.",
        title='Legal Tags',
    )
    createUser: Optional[str] = Field(
        None,
        description='The user reference, which created the first version of this resource object. Set by the System.',
        example='some-user@some-company-cloud.com',
        title='Resource Object Creation User Reference',
    )
    id: Optional[
        constr(
            regex=r'^[\w\-\.]+:work-product-component\-\-SlimTubeTest:[\w\-\.\:\%]+$'
        )
    ] = Field(
        None,
        description='Previously called ResourceID or SRN which identifies this OSDU resource object without version.',
        example='namespace:work-product-component--SlimTubeTest:dd76cf6c-226f-5636-ad1b-1ca0f8249cc8',
        title='SlimTubeTestID',
    )
