#  Copyright 2023 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  /api/schema-service/v1/schema/osdu:wks:work-product-component--SamplesAnalysis:1.0.0
#   timestamp: 2023-10-19T20:18:16+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field, constr


class Field0(BaseModel):
    EffectiveDateTime: Optional[datetime] = Field(
        None,
        description="The date and time at which the activity status becomes effective.",
        title="Effective Date Time",
    )
    TerminationDateTime: Optional[datetime] = Field(
        None,
        description="The date and time at which the activity status is no longer in effect. For still effective activity states, the TerminationDateTime is left absent. For zero-duration intervals (events), the TerminationDateTime set to the same value as EffectiveDateTime.",
        title="Termination Date Time",
    )
    ActivityStatusID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-ActivityStatus:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="The ActivityStatus is a set of major activity phases that are significant to business stakeholders.",
        title="Activity Status ID",
    )
    Remark: Optional[str] = Field(
        None,
        description="An optional remark associated with the ActivityStatus and time interval.",
        title="Remark",
    )
