#  Copyright 2023 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  extraction_data_schema.json
#   timestamp: 2023-09-18T16:55:34+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field, constr


class MassOfRockExtracted(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class MassOfExtract(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class ExtractByRockMass(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class ExtractOfTotalOrganicCarbon(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class Model(BaseModel):
    SamplesAnalysisID: constr(
        regex=r"^[\w\-\.]+:work-product-component\-\-SamplesAnalysis:[\w\-\.\:\%]+:[0-9]*$"
    )
    SampleID: constr(regex=r"^[\w\-\.]+:master-data\-\-Sample:[\w\-\.\:\%]+:[0-9]*$")
    Method: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-GeochemistryMethod:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(None, description="The sample analysis method used for this analysis")
    MassOfRockExtracted: Optional[MassOfRockExtracted] = Field(
        None,
        description="mass of the rock sample that has been submitted for extraction. note - may be a fraction of the whole rock sample",
    )
    MassOfExtract: Optional[MassOfExtract] = Field(
        None, description="mass of fluid extract obtained from parent rock sample"
    )
    ExtractByRockMass: Optional[ExtractByRockMass] = Field(
        None,
        description="extract yield: mass of extract / mass of parent rock sample",
    )
    ExtractOfTotalOrganicCarbon: Optional[ExtractOfTotalOrganicCarbon] = Field(
        None, description="mass of extract as a percentage of Total Organic Carbon"
    )
