#  Copyright 2023 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  interfacial_tension_data_schema.json
#   timestamp: 2023-05-08T10:00:14+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, constr


class WettingPhase(Enum):
    aqueous = 'aqueous'
    oleic = 'oleic'
    vapor = 'vapor'
    total_hydrocarbon = 'total hydrocarbon'


class NonWettingPhase(Enum):
    aqueous = 'aqueous'
    oleic = 'oleic'
    vapor = 'vapor'
    total_hydrocarbon = 'total hydrocarbon'


class ComponentMassFraction(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+')
    ] = None


class ComponentMoleFraction(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+')
    ] = None


class SurfactantItem(BaseModel):
    ComponentName: Optional[str] = None
    ComponentMassFraction: Optional[ComponentMassFraction] = None
    ComponentMoleFraction: Optional[ComponentMoleFraction] = None


class StepPressure(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+')
    ] = None


class StepTemperature(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+')
    ] = None


class SurfactantConcentration(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+')
    ] = None


class InterfacialTension(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+')
    ] = None


class InterfacialTensionTestStep(BaseModel):
    StepNumber: Optional[str] = Field(
        None,
        description='Internal step number which identifies the sequence of step in interfacial tension measurements',
        title='Step Number',
    )
    StepPressure: Optional[StepPressure] = None
    StepTemperature: Optional[StepTemperature] = None
    WettingPhaseSaturation: Optional[float] = None
    SurfactantConcentration: Optional[SurfactantConcentration] = None
    InterfacialTension: Optional[InterfacialTension] = None
    Remark: Optional[str] = Field(None, title='Remark')


class Model(BaseModel):
    InterfacialTensionTestID: constr(
        regex=r'^[\w\-\.]+:work-product-component\-\-InterfacialTensionTest:[\w\-\.\:\%]+:[0-9]*$'
    ) = Field(..., title='Interfacial Tension Test ID')
    TestNumber: Optional[str] = Field(
        None,
        description='A number for this test for purposes of e.g., tracking lab sequence.',
        title='Test Number',
    )
    FluidSampleID: Optional[
        constr(regex=r'^[\w\-\.]+:master-data\-\-FluidSample:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(
        None,
        description='Unique identifier of the Fluid Sample which Atmospheric Flash and Compositional Analysis is done on',
        title='Fluid Sample ID',
    )
    WettingPhase: Optional[WettingPhase] = Field(
        None, description='aqueous/oleic/vapor/total hydrocarbon'
    )
    nonWettingPhase: Optional[NonWettingPhase] = Field(
        None, description='aqueous/oleic/vapor/total hydrocarbon'
    )
    Surfactant: Optional[List[SurfactantItem]] = None
    Remark: Optional[str] = Field(None, title='Remark')
    InterfacialTensionTestSteps: Optional[List[InterfacialTensionTestStep]] = None
