#  Copyright 2023 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  transport_test_data_schema.json
#   timestamp: 2023-04-12T07:32:12+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, constr


class TestTemperature(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class SaturationPressure(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class StepPressure(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class OilViscosity(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class GasViscosity(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class TransportTestStep(BaseModel):
    StepNumber: Optional[str] = Field(
        None,
        description='Internal step number which identifies the sequence of step in transport test measurements',
        title='Step Number',
    )
    StepPressure: Optional[StepPressure] = None
    OilViscosity: Optional[OilViscosity] = None
    GasViscosity: Optional[GasViscosity] = None


class Model(BaseModel):
    TransportTestID: constr(
        regex=r'^[\w\-\.]+:work-product-component\-\-TransportTest:[\w\-\.\:\%]+:[0-9]*$'
    ) = Field(..., title='Transport Test ID')
    TestNumber: Optional[str] = Field(
        None,
        description='A number for this test for purposes of e.g., tracking lab sequence.',
        title='Test Number',
    )
    FluidSampleID: Optional[
        constr(regex=r'^[\w\-\.]+:master-data\-\-FluidSample:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(
        None,
        description='Unique identifier of the Fluid Sample which Atmospheric Flash and Compositional Analysis is done on',
        title='Fluid Sample ID',
    )
    TestTemperature: Optional[TestTemperature] = None
    SaturationPressure: Optional[SaturationPressure] = None
    TransportTestSteps: Optional[List[TransportTestStep]] = None
