#  Copyright 2023 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  vle_data_schema.json
#   timestamp: 2023-05-16T09:22:19+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, constr


class TestTemperature(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+')
    ] = None


class TestPressure(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+')
    ] = None


class GasSolventAdded(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+')
    ] = None


class MixtureVolume(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+')
    ] = None


class MixtureGasSolventMoleFraction(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+')
    ] = None


class MixtureGOR(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+')
    ] = None


class MixturePsatTestTemperature(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+')
    ] = None


class MixtureRelativeVolumeRelativeToPsat(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+')
    ] = None


class VaporPhaseVolume(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+')
    ] = None


class VaporPhaseViscosity(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+')
    ] = None


class VaporPhaseDensity(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+')
    ] = None


class LiquidPhaseVolume(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+')
    ] = None


class LiquidPhaseDensity(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+')
    ] = None


class MoleFraction(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+')
    ] = None


class MassFraction(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+')
    ] = None


class VaporCompositionItem(BaseModel):
    ComponentName: Optional[str] = None
    MoleFraction: Optional[MoleFraction] = None
    MassFraction: Optional[MassFraction] = None


class LiquidCompositionItem(BaseModel):
    ComponentName: Optional[str] = None
    MoleFraction: Optional[MoleFraction] = None
    MassFraction: Optional[MassFraction] = None


class Model(BaseModel):
    VaporLiquidEquilibriumTestID: constr(
        regex=r'^[\w\-\.]+:work-product-component--VaporLiquidEquilibriumTest:[\w\-\.\:\%]+:[0-9]*$'
    )
    FluidSampleID: Optional[
        constr(regex=r'^[\w\-\.]+:master-data--FluidSample:[\w\-\.\:\%]+:[0-9]*$')
    ] = None
    TestNumber: Optional[str] = None
    TestTemperature: Optional[TestTemperature] = Field(None, title='Test Temperature')
    TestPressure: Optional[TestPressure] = Field(None, title='Test Pressure')
    GasSolventAdded: Optional[GasSolventAdded] = Field(None, title='Gas Solvent Added')
    MixtureVolume: Optional[MixtureVolume] = Field(None, title='Mixture Volume')
    MixtureGasSolventMoleFraction: Optional[MixtureGasSolventMoleFraction] = Field(
        None, title='Mixture Gas Solvent Mole Fraction'
    )
    MixtureGOR: Optional[MixtureGOR] = Field(None, title='Mixture GOR')
    MixturePsatTestTemperature: Optional[MixturePsatTestTemperature] = Field(
        None, title='Mixture Psat Test Temperature'
    )
    MixtureRelativeVolumeRelativeToPsat: Optional[
        MixtureRelativeVolumeRelativeToPsat
    ] = Field(None, title='Mixture Relative Volume Relative To Psat')
    AtmosphericFlashTestReference: Optional[str] = None
    InjectedGasAdded: Optional[str] = None
    CumulativeGasAdded: Optional[str] = None
    VaporPhaseVolume: Optional[VaporPhaseVolume] = Field(
        None, title='Vapor Phase Volume'
    )
    VaporPhaseViscosity: Optional[VaporPhaseViscosity] = Field(
        None, title='Vapor Phase Viscosity'
    )
    VaporPhaseDensity: Optional[VaporPhaseDensity] = Field(
        None, title='Vapor Phase Density'
    )
    LiquidPhaseVolume: Optional[LiquidPhaseVolume] = Field(
        None, title='Liquid Phase Volume'
    )
    LiquidPhaseDensity: Optional[LiquidPhaseDensity] = Field(
        None, title='Liquid Phase Density'
    )
    VaporComposition: Optional[List[VaporCompositionItem]] = None
    VaporTransportTestReference: Optional[str] = None
    LiquidTransportTestReference: Optional[str] = None
    LiquidComposition: Optional[List[LiquidCompositionItem]] = None
    Remark: Optional[str] = None
