#  Copyright 2024 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  CapillaryPressureDataSchema.1.0.0.json
#   timestamp: 2024-12-10T15:10:29+00:00

from __future__ import annotations

from app.models.config import RafsBaseModel

from datetime import date
from typing import List, Optional

from pydantic import Extra, Field, constr


class TransientDatum(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    ProductionProfile: Optional[float] = Field(
        None,
        description="Production of displaced phase as function of time in a centrifuge or porous plate experiment.",
        title="Production Profile",
    )
    Time: Optional[float] = Field(
        None,
        description="The time at which this production profile value was measured.",
        title="Time",
    )
    RotationalSpeed: Optional[float] = Field(
        None,
        description="The rotational speed of the centrifuge, measured as rotations per minute (RPM) or equivalent.",
        title="Rotational Speed",
    )


class Permeability(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = Field(
        None,
        description="The numeric value of this permeability measurement.",
        title="Value",
    )
    PermeabilityMeasurementTypeID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-PermeabilityMeasurementType:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="The OSDU reference-data ID corresponding to the type of permeability being measured.",
        title="Permeability Measurement Type ID",
    )


class Porosity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = Field(
        None,
        description="The numeric value of this porosity measurement.",
        title="Value",
    )
    PorosityMeasurementTypeID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-PorosityMeasurementType:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="The OSDU reference-data ID corresponding to the type of porosity being measured.",
        title="Porosity Measurement Type ID",
    )


class Pressure(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = Field(
        None,
        description="The numeric value of this pressure measurement.",
        title="Value",
    )
    PressureMeasurementTypeID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-PressureMeasurementType:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="The OSDU reference-data ID corresponding to the type of pressure being measured.",
        title="Pressure Measurement Type ID",
    )


class Remark(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    RemarkSequenceNumber: Optional[int] = Field(
        None,
        description="A unique identifier for each remark record. This identifier is used to uniquely identify a member in an array of remarks.",
        example=1,
        title="Remark Sequence Number",
    )
    Remark: Optional[str] = Field(
        None, description="A descriptive comment for this remark.", title="Remark"
    )
    RemarkSource: Optional[str] = Field(
        None,
        description="The person, vendor, interpreter or other provider of information.",
        title="Remark Source",
    )
    RemarkDate: Optional[date] = Field(
        None, description="The date the remark was issued.", title="Remark Date"
    )


class CalculatedProperties(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    PoreThroatRadius: Optional[float] = Field(
        None,
        description="PoreThroatRadius is the conversion of the capillary pressure using interfacial tension and the wettability angle ( PTR = 2 x sigma cos (theta) / Capillary pressure )",
        title="Pore Throat Radius",
    )
    PoreThroatMedianRadius: Optional[float] = Field(
        None,
        description="This is the P50 (median) of the Pore Throat Radius distribution.",
        title="Pore Throat Median Radius",
    )
    EndFaceEstimationMethodID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-EndFaceEstimationMethod:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="The method used to calculate the end face phase saturation, e.g. HasslerBrunner,\nForbes.",
        title="End Face Estimation Method ID",
    )
    EndFacePhaseSaturation: Optional[float] = Field(
        None,
        description="Calculated saturation of the end face of the sample in a centrifuge experiment.",
        title="End Face Phase Saturation",
    )
    JFunction: Optional[float] = Field(
        None,
        description="Conversion of normalized capillary pressure using porosity and permeability [ J = PC / ( sigma x cos wettability ) x SQRT( permeability / porosity ) ]",
        title="J Function",
    )
    CapillaryPressure: Optional[float] = Field(
        None,
        description="A measure of the difference in pressure across the interface between two phases, which are typically oil/water, gas/water or gas/oil.",
        title="Capillary Pressure",
    )
    NormalizedPermeabilityDistributionFunction: Optional[float] = Field(
        None,
        description="The computation of a permeability obtained from the contribution of the different pore throats as they are filled during the experiment. related to HPMI or MICP only.",
        title="Normalized Permeability Distribution Function",
    )
    PoreThroatSizeDistribution: Optional[List[float]] = Field(
        None,
        description="The distribution of pore throat size during the experiment.",
        title="Pore Throat Size Distribution",
    )
    MeanHydraulicRadius: Optional[float] = Field(
        None,
        description="Term used for for SQRT( permeability / porosity ) which is homogeneous to a length (mD ~ m^2)",
        title="Mean Hydraulic Radius",
    )
    CumulativePhaseSaturation: Optional[float] = Field(
        None,
        description="This is the computed saturation for the cumulative volume that is normalized to the volume at the end of the experiment.",
        title="Cumulative Phase Saturation",
    )
    PhaseSaturationFrequency: Optional[float] = Field(
        None,
        description="This is the frequency plot of the portion of porosity filled at each pressure step.",
        title="Phase Saturation Frequency",
    )
    BondNumber: Optional[float] = Field(
        None,
        description="A dimensionless number that characterizes the relative importance of gravitational forces to capillary forces within a fluid system.",
        title="Bond Number",
    )


class TestDatum(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    TransientData: Optional[List[TransientDatum]] = Field(
        None,
        description="Object containing volume measurements over time for centrifuge and porous plate analyses.",
        title="Transient Data",
    )
    Permeability: Optional[Permeability] = Field(
        None,
        description="Quantifies the ability for fluids or gas to flow through a sample.",
        title="Permeability",
    )
    Porosity: Optional[Porosity] = Field(
        None,
        description="The amount of pore space relative to the volume of a sample.",
        title="Porosity",
    )
    Pressure: Optional[Pressure] = Field(
        None,
        description="The value and unit of measure of the pressure of the sample environment.",
        title="Pressure",
    )
    Temperature: Optional[float] = Field(
        None,
        description="The value and unit of measure of the temperature of the sample environment.",
        title="Temperature",
    )
    InterfacialTension: Optional[float] = Field(
        None,
        description="The force that holds the surface of a particular phase together.",
        title="Interfacial Tension",
    )
    StepNumber: Optional[float] = Field(
        None,
        description="Number assigned to identify this specific step in the sequence of steps of the analysis.",
        title="Step Number",
    )
    CapillaryPressure: Optional[float] = Field(
        None,
        description="A measure of the difference in pressure across the interface between two phases, which are typically oil/water, gas/water or gas/oil.",
        title="Capillary Pressure",
    )
    PhaseSaturation: Optional[float] = Field(
        None,
        description="The saturation of the sample for this step.",
        title="Phase Saturation",
    )
    PhaseInjectedVolume: Optional[float] = Field(
        None,
        description="The volume and type of fluid injected into the sample for this step.  This volume is identical to the volume of fluid produced from the sample.",
        title="Phase Injected Volume",
    )
    Remark: Optional[Remark] = Field(
        None,
        description="Additional notes or observations relevant to the specific test step.",
        title="Remark",
    )
    CalculatedProperties: Optional[CalculatedProperties] = Field(
        None,
        description="Object containing calculated properties such as averages, Jfunction, and height above free water level.",
        title="Calculated Properties",
    )
    RotationalSpeed: Optional[float] = Field(
        None,
        description="The rotational speed of the centrifuge, measured as rotations per minute (RPM) or equivalent.",
        title="rotational Speed",
    )
    StartTime: Optional[float] = Field(
        None,
        description="Timestamp at which this step is initiated.",
        title="Start Time",
    )
    CumulativeIntrusion: Optional[float] = Field(
        None,
        description="The accumulated intrusion at this test step, typically reported as mL/gram.",
        title="Cumulative Intrusion",
    )


class Endpoints(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    CapillaryPressureMax: Optional[float] = Field(
        None,
        description="Maximum capillary pressure recorded during the analysis of the sample",
        title="Capillary Pressure Maximum",
    )
    PhaseSaturationAtCapillaryPressureMax: Optional[float] = Field(
        None,
        description="Saturation at the maximum capillary pressure of this phase of the experiment.",
        title="Phase Saturation At Capillary Pressure Maximum",
    )
    LowestPhaseSaturationAvg: Optional[float] = Field(
        None,
        description="Lowest phase saturation achieved averaged over entire core plug or composite, only applicable for centrifuge & coreflood",
        title="Lowest Phase Saturation Average",
    )
    MinCapPressureRecorded: Optional[float] = Field(
        None,
        description="Minimum pressure from which Sor can be obtained.",
        title="Minimum Capillary Pressure Recorded",
    )
    ResidualFluidSaturation: Optional[float] = Field(
        None,
        description="The saturation of residual fluid after forced imbibition or drainage.",
        title="Residual Fluid Saturation",
    )
    EffectivePermeabilityOfResidualFluid: Optional[float] = Field(
        None,
        description="The effective permeability of the residual fluid at the end of the imbibition or drainage phase.",
        title="Effective Permeability Of Residual Fluid",
    )
    RelativePermeabilityOfResidualFluid: Optional[float] = Field(
        None,
        description="The relative permeability of the residual fluid at the end of the imbibition or drainage phase.",
        title="Relative Permeability Of Residual Fluid",
    )


class ForcedImbibition(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    InitialWaterSaturation: Optional[float] = Field(
        None,
        description="Water Saturation of the sample at initial pressure and temperature conditions.",
        title="Initial Water Saturation",
    )
    TestData: Optional[List[TestDatum]] = Field(
        None,
        description="The permeability value acting as a reference for this experiment.",
        title="Test Data",
    )
    Endpoints: Optional[Endpoints] = Field(
        None,
        description="The type of permeability measurement being used as a reference value for this experiment.",
        title="Endpoints",
    )
    InjectionFluidID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-SampleInjectionFluidType:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="The injection fluid used during this phase of the experiment.",
        title="Injection Fluid Type ID",
    )
    SpontaneousImbibition: Optional[float] = Field(
        None,
        description="The fraction of injection fluid imbibed spontaneously prior to forced injection.",
        title="Spontaneous Imbibition",
    )
    WOGnCycleNotationID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-WOGnCycleNotation:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="The WOGn notation description of this capillary pressure cycle.",
        title="Water Oil Gas Number ID",
    )
    EndTime: Optional[float] = Field(
        None, description="Overall duration of the test.", title="End Time"
    )


class TestDatum1(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    TransientData: Optional[List[TransientDatum]] = Field(
        None,
        description="Object containing volume measurements over time for centrifuge and porous plate analyses.",
        title="Transient Data",
    )
    Permeability: Optional[Permeability] = Field(
        None,
        description="Quantifies the ability for fluids or gas to flow through a sample.",
        title="Permeability",
    )
    Porosity: Optional[Porosity] = Field(
        None,
        description="The amount of pore space relative to the volume of a sample.",
        title="Porosity",
    )
    Pressure: Optional[Pressure] = Field(
        None,
        description="The value and unit of measure of the pressure of the sample environment.",
        title="Pressure",
    )
    Temperature: Optional[float] = Field(
        None,
        description="The value and unit of measure of the temperature of the sample environment.",
        title="Temperature",
    )
    InterfacialTension: Optional[float] = Field(
        None,
        description="The force that holds the surface of a particular phase together.",
        title="Interfacial Tension",
    )
    StepNumber: Optional[float] = Field(
        None,
        description="Number assigned to identify this specific step in the sequence of steps of the analysis.",
        title="Step Number",
    )
    CapillaryPressure: Optional[float] = Field(
        None,
        description="A measure of the difference in pressure across the interface between two phases, which are typically oil/water, gas/water or gas/oil.",
        title="Capillary Pressure",
    )
    PhaseSaturation: Optional[float] = Field(
        None,
        description="The saturation of the sample for this step.",
        title="Phase Saturation",
    )
    PhaseInjectedVolume: Optional[float] = Field(
        None,
        description="The volume and type of fluid injected into the sample for this step.  This volume is identical to the volume of fluid produced from the sample.",
        title="Phase Injected Volume",
    )
    Remark: Optional[Remark] = Field(
        None,
        description="Additional notes or observations relevant to the specific test step.",
        title="Remark",
    )
    CalculatedProperties: Optional[CalculatedProperties] = Field(
        None,
        description="Object containing calculated properties such as averages, Jfunction, and height above free water level.",
        title="Calculated Properties",
    )
    RotationalSpeed: Optional[float] = Field(
        None,
        description="The rotational speed of the centrifuge, measured as rotations per minute (RPM) or equivalent.",
        title="rotational Speed",
    )
    StartTime: Optional[float] = Field(
        None,
        description="Timestamp at which this step is initiated.",
        title="Start Time",
    )
    CumulativeIntrusion: Optional[float] = Field(
        None,
        description="The accumulated intrusion at this test step, typically reported as mL/gram.",
        title="Cumulative Intrusion",
    )


class ForcedDrainage(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    InitialWaterSaturation: Optional[float] = Field(
        None,
        description="Water Saturation of the sample at initial pressure and temperature conditions.",
        title="Initial Water Saturation",
    )
    TestData: Optional[List[TestDatum1]] = Field(
        None,
        description="The permeability value acting as a reference for this experiment.",
        title="Test Data",
    )
    Endpoints: Optional[Endpoints] = Field(
        None,
        description="The type of permeability measurement being used as a reference value for this experiment.",
        title="Endpoints",
    )
    InjectionFluidID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-SampleInjectionFluidType:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="The injection fluid used during this phase of the experiment.",
        title="Injection Fluid Type ID",
    )
    SpontaneousImbibition: Optional[float] = Field(
        None,
        description="The fraction of injection fluid imbibed spontaneously prior to forced injection.",
        title="Spontaneous Imbibition",
    )
    WOGnCycleNotationID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-WOGnCycleNotation:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="The WOGn notation description of this capillary pressure cycle.",
        title="Water Oil Gas Number Cycle Notation ID",
    )
    EndTime: Optional[float] = Field(
        None, description="Overall duration of the test.", title="End Time"
    )


class InitialConditions(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Pressure: float = Field(
        ...,
        description="The recorded absolute pressure condition. The unit of measure context is defined via meta[] in the Storage record while the Search responses return the value in base SI unit Pa (Pascal).",
        example="1 bar",
        title="Pressure",
    )
    Temperature: float = Field(
        ...,
        description="The recorded temperature condition. The unit of measure context is defined via meta[] in the Storage record while the Search responses return the value in base SI unit K (Kelvin).",
        example="15 degC",
        title="Temperature",
    )
    IsStandardConditions: Optional[bool] = Field(
        None,
        description="To capture when Measurement have been made at Standard Conditions (25°C / 100 kPa)\nMutually Exclusive with Pressure/Temperature.\nCapture",
        title="Is Standard Conditions",
    )
    NonStandardConditionsReference: Optional[str] = Field(
        None,
        description='Open Text Box to capture the P & T Reference when measurements are made at non standard conditions (such as "Reservoir", "Tank",…)',
        title="Non Standard Conditions Reference",
    )


class ReferencePermeabilityItem(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = Field(
        None,
        description="The permeability value acting as a reference for this experiment.",
        title="Value",
    )
    PermeabilityMeasurementTypeID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-PermeabilityMeasurementType:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="The type of permeability measurement being used as a reference value for this experiment.",
        title="Permeability Measurement Type ID",
    )


class CapillaryPressureModel100(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    SamplesAnalysisID: constr(
        regex=r"^[\w\-\.]+:work-product-component\-\-SamplesAnalysis:[\w\-\.\:\%]+:[0-9]*$"
    ) = Field(
        ...,
        description="The OSDU Identifier for this SamplesAnalysis.",
        title="Sample Analysis ID",
    )
    SampleID: constr(
        regex=r"^[\w\-\.]+:master-data\-\-Sample:[\w\-\.\:\%]+:[0-9]*$"
    ) = Field(
        ...,
        description="The OSDU Identifier for the Sample associated with this analysis.",
        title="Sample ID",
    )
    SaturationProcessMethodID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-SaturationProcessMethod:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="SaturationProcessMethod, intended to be paired with SampleAnalysisType for Capillary Pressure Subfamilies.  e.g. PrimaryDrainage, PrimaryImbibition, SecondaryDrainage, SecondaryImbibition, TertiaryDrainage.",
        title="Saturation Process Method ID",
    )
    FluidSystemAnalysisTypeID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-FluidSystemAnalysisType:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="Identifier for the Fluid System (e.g. oil-brine) that is present in this sample.",
        title="Fluid System Analysis Type ID",
    )
    ForcedImbibition: Optional[ForcedImbibition] = Field(
        None,
        description="Array Object containing the test steps for this analysis.",
        title="Forced Imbibition",
    )
    ForcedDrainage: Optional[ForcedDrainage] = Field(
        None,
        description="Array Object containing the test steps for this analysis.",
        title="Forced Drainage",
    )
    InitialOilSaturation: Optional[float] = Field(
        None,
        description="Oil Saturation of the sample at initial pressure and temperature conditions.",
        title="Initial Oil Saturation",
    )
    InitialGasSaturation: Optional[float] = Field(
        None,
        description="Gas Saturation of the sample at initial pressure and temperature conditions.",
        title="Initial Gas Saturation",
    )
    BrineSalinity: Optional[float] = Field(
        None,
        description="The concentration of salt within brine which may be called saturant or saturant brine.",
        title="Brine Salinity",
    )
    InitialConditions: Optional[InitialConditions] = Field(
        None,
        description="The pressure and temperature condition of the sample when the secondary phase is introduced.",
        title="Initial Conditions",
    )
    AppliedOverBurdenStress: Optional[float] = Field(
        None,
        description="Pressure applied on the sample with sleeve(s) prior to the capillary pressure experiment, also known as Net Overburden Pressure (NOBP), or Net confining stress (NCS).",
        title="Applied Over Burden Stress",
    )
    DesaturationMethodID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-DesaturationMethod:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="The method by which the sample was desaturated.",
        title="Desaturation Method ID",
    )
    MeanDistanceImbibition: Optional[float] = Field(
        None,
        description="The average length of the arm of the centrifuge for the imbibition phase of the experiment.",
        title="Mean Distance Imbibition",
    )
    MeanDistanceDrainage: Optional[float] = Field(
        None,
        description="The average length of the arm of the centrifuge for the drainage phase of the experiment.",
        title="Mean Distance Drainage",
    )
    ReferencePermeability: Optional[List[ReferencePermeabilityItem]] = Field(
        None,
        description="e.g. gas permeability kg, gas permeability at minimum liquid saturation kg@Slmin, oil permeability ko, water permeability kw, etc",
        title="Reference Permeability",
    )
    WaterViscosity: Optional[float] = Field(
        None,
        description="A measure of the water's internal resistance to flow.",
        title="Water Viscosity",
    )
    WaterDensity: Optional[float] = Field(
        None,
        description="The mass per volume of water in the sample.",
        title="Water Density",
    )
    OilViscosity: Optional[float] = Field(
        None,
        description="A measure of the oil’s internal resistance to flow.",
        title="Oil Viscosity",
    )
    OilDensity: Optional[float] = Field(
        None,
        description="The mass per volume of oil in the sample.",
        title="Oil Density",
    )
    GasViscosity: Optional[float] = Field(
        None,
        description="A measure of the gas’s internal resistance to flow.",
        title="Gas Viscosity",
    )
    GasDensity: Optional[float] = Field(
        None,
        description="The mass per volume of gas in the sample.",
        title="Gas Density",
    )
    OilTypeID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-DisplacedFluidType:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="Identifies the type of oil used in the experiment.",
        title="Oil Type ID",
    )
    GasTypeID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-SampleInjectionFluidType:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="Identifies the type of gas used in the experiment.",
        title="Gas Type ID",
    )
    WaterTypeID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-SampleInjectionFluidType:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="Identifies the type of gas used in the experiment.",
        title="Water Type ID",
    )
