#  Copyright 2024 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  coefficient_table_data_schema.json
#   timestamp: 2024-02-08T17:33:04+00:00

from __future__ import annotations

from datetime import date
from typing import List, Optional

from pydantic import Extra, constr

from app.models.config import RafsBaseModel


class Temperature(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class Pressure(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class CalibrationMatrixItem(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Temperature: Optional[Temperature] = None
    Pressure: Optional[Pressure] = None
    Calibration: Optional[float] = None


class Calibration(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    CalibrationType: Optional[str] = None
    CalibrationMatrix: Optional[List[CalibrationMatrixItem]] = None


class Model(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    CalibrationDate: Optional[date] = None
    Calibrations: Optional[List[Calibration]] = None
