#  Copyright 2024 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  constant_composition_expansion.1.0.0.json
#   timestamp: 2025-02-05T17:21:35+00:00

from __future__ import annotations

from app.models.config import RafsBaseModel

from datetime import date
from typing import List, Optional, Union

from pydantic import Extra, Field, constr


class Meta(RafsBaseModel):
    kind: str = Field(
        "Unit",
        const=True,
        description="The kind of reference, 'Unit' for FrameOfReferenceUOM.",
        title="UOM Reference Kind",
    )
    name: Optional[str] = Field(
        None,
        description="The unit symbol or name of the unit.",
        example="ft[US]",
        title="UOM Unit Symbol",
    )
    persistableReference: Optional[str] = Field(
        None,
        description="The self-contained, persistable reference string uniquely identifying the Unit.",
        example='{"abcd":{"a":0.0,"b":1200.0,"c":3937.0,"d":0.0},"symbol":"ft[US]","baseMeasurement":{"ancestry":"L","type":"UM"},"type":"UAD"}',
        title="UOM Persistable Reference",
    )
    unitOfMeasureID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="SRN to unit of measure reference.",
        example="namespace:reference-data--UnitOfMeasure:ftUS:",
    )
    propertyNames: Optional[List[str]] = Field(
        None,
        description='The list of property names, to which this meta data item provides Unit context to. A full path like "StructureA.PropertyB" is required to define a unique context; "data" is omitted since frame-of reference normalization only applies to the data block.',
        example=["HorizontalDeflection.EastWest", "HorizontalDeflection.NorthSouth"],
        title="UOM Property Names",
    )


class Meta1(RafsBaseModel):
    kind: str = Field(
        "CRS",
        const=True,
        description="The kind of reference, constant 'CRS' for FrameOfReferenceCRS.",
        title="CRS Reference Kind",
    )
    name: Optional[str] = Field(
        None,
        description="The name of the CRS.",
        example="WGS 84 / UTM zone 15N",
        title="CRS Name",
    )
    persistableReference: str = Field(
        ...,
        description="The self-contained, persistable reference string uniquely identifying the CRS.",
        example='{"authCode":{"auth":"EPSG","code":"32615"},"name":"WGS_1984_UTM_Zone_15N","type":"LBC","ver":"PE_10_9_1","wkt":"PROJCS[\\"WGS_1984_UTM_Zone_15N\\",GEOGCS[\\"GCS_WGS_1984\\",DATUM[\\"D_WGS_1984\\",SPHEROID[\\"WGS_1984\\",6378137.0,298.257223563]],PRIMEM[\\"Greenwich\\",0.0],UNIT[\\"Degree\\",0.0174532925199433]],PROJECTION[\\"Transverse_Mercator\\"],PARAMETER[\\"False_Easting\\",500000.0],PARAMETER[\\"False_Northing\\",0.0],PARAMETER[\\"Central_Meridian\\",-93.0],PARAMETER[\\"Scale_Factor\\",0.9996],PARAMETER[\\"Latitude_Of_Origin\\",0.0],UNIT[\\"Meter\\",1.0],AUTHORITY[\\"EPSG\\",32615]]"}',
        title="CRS Persistable Reference",
    )
    coordinateReferenceSystemID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-CoordinateReferenceSystem:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="SRN to CRS reference.",
        example="namespace:reference-data--CoordinateReferenceSystem:Projected:EPSG::32615:",
    )
    propertyNames: Optional[List[str]] = Field(
        None,
        description='The list of property names, to which this meta data item provides CRS context to. A full path like "StructureA.PropertyB" is required to define a unique context; "data" is omitted since frame-of reference normalization only applies to the data block.',
        example=["KickOffPosition.X", "KickOffPosition.Y"],
        title="CRS Property Names",
    )


class Meta2(RafsBaseModel):
    kind: str = Field(
        "DateTime",
        const=True,
        description="The kind of reference, constant 'DateTime', for FrameOfReferenceDateTime.",
        title="DateTime Reference Kind",
    )
    name: Optional[str] = Field(
        None,
        description="The name of the DateTime format and reference.",
        example="UTC",
        title="DateTime Name",
    )
    persistableReference: str = Field(
        ...,
        description="The self-contained, persistable reference string uniquely identifying DateTime reference.",
        example='{"format":"yyyy-MM-ddTHH:mm:ssZ","timeZone":"UTC","type":"DTM"}',
        title="DateTime Persistable Reference",
    )
    propertyNames: Optional[List[str]] = Field(
        None,
        description='The list of property names, to which this meta data item provides DateTime context to. A full path like "StructureA.PropertyB" is required to define a unique context; "data" is omitted since frame-of reference normalization only applies to the data block.',
        example=["Acquisition.StartTime", "Acquisition.EndTime"],
        title="DateTime Property Names",
    )


class Meta3(RafsBaseModel):
    kind: str = Field(
        "AzimuthReference",
        const=True,
        description="The kind of reference, constant 'AzimuthReference', for FrameOfReferenceAzimuthReference.",
        title="AzimuthReference Reference Kind",
    )
    name: Optional[str] = Field(
        None,
        description="The name of the CRS or the symbol/name of the unit.",
        example="TrueNorth",
        title="AzimuthReference Name",
    )
    persistableReference: str = Field(
        ...,
        description="The self-contained, persistable reference string uniquely identifying AzimuthReference.",
        example='{"code":"TrueNorth","type":"AZR"}',
        title="AzimuthReference Persistable Reference",
    )
    propertyNames: Optional[List[str]] = Field(
        None,
        description='The list of property names, to which this meta data item provides AzimuthReference context to. A full path like "StructureA.PropertyB" is required to define a unique context; "data" is omitted since frame-of reference normalization only applies to the data block.',
        example=["Bearing"],
        title="AzimuthReference Property Names",
    )


class VaporCompositionItem(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    ComponentNameID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-SampleCompositionComponent:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="Name of the component in the liquid.",
        title="Component Name ID",
    )
    RelativeMoleWeight: Optional[float] = Field(
        None,
        description="Molar mass relative to other components.",
        title="Relative Mole Weight",
    )
    MolecularWeight: Optional[float] = Field(
        None,
        description="The molecular weight of the component.",
        title="Molecular Weight",
    )
    MolePercent: Optional[float] = Field(
        None,
        description="The molar percentage of the component, if available.",
        title="Mole Percent",
    )
    MassPercent: Optional[float] = Field(
        None,
        description="The mass percentage of the component, if available.",
        title="Mass Percent",
    )
    VolumePercent: Optional[float] = Field(
        None,
        description="The volume percentage of the component, if available.",
        title="Volume Percent",
    )
    SpecificGravity: Optional[float] = Field(
        None,
        description="The specific gravity of the component.",
        title="Specific Gravity",
    )


class LiquidCompositionItem(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    ComponentNameID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-SampleCompositionComponent:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="Name of the component in the liquid.",
        title="Component Name ID",
    )
    RelativeMoleWeight: Optional[float] = Field(
        None,
        description="Molar mass relative to other components.",
        title="Relative Mole Weight",
    )
    MolecularWeight: Optional[float] = Field(
        None,
        description="The molecular weight of the component.",
        title="Molecular Weight",
    )
    MolePercent: Optional[float] = Field(
        None,
        description="The molar percentage of the component, if available.",
        title="Mole Percent",
    )
    MassPercent: Optional[float] = Field(
        None,
        description="The mass percentage of the component, if available.",
        title="Mass Percent",
    )
    VolumePercent: Optional[float] = Field(
        None,
        description="The volume percentage of the component, if available.",
        title="Volume Percent",
    )
    SpecificGravity: Optional[float] = Field(
        None,
        description="The specific gravity of the component.",
        title="Specific Gravity",
    )


class Remark(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    RemarkSequenceNumber: Optional[int] = Field(
        None,
        description="A unique identifier for each remark record. This identifier is used to uniquely identify a member in an array of remarks.",
        example=1,
        title="Remark Sequence Number",
    )
    Remark: Optional[str] = Field(
        None, description="A descriptive comment for this remark.", title="Remark"
    )
    RemarkSource: Optional[str] = Field(
        None,
        description="The person, vendor, interpreter or other provider of information.",
        title="Remark Source",
    )
    RemarkDate: Optional[date] = Field(
        None, description="The date the remark was issued.", title="Remark Date"
    )


class TestStep(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    StepNumber: Optional[float] = Field(
        None,
        description="Internal step number which identifies the sequence of step in CCE measurements.",
        title="Step Number",
    )
    StepPressure: Optional[float] = Field(
        None, description="The pressure applied during the step.", title="Step Pressure"
    )
    LiquidVolumeRelativeToSaturationPressureVolume: Optional[float] = Field(
        None,
        description="Volume of liquid relative to the volume at saturation pressure.",
        title="Liquid Volume Relative To Saturation Pressure Volume",
    )
    OilDensity: Optional[float] = Field(
        None,
        description="The density of the oil for this test step.",
        title="Oil Density",
    )
    OilCompressibility: Optional[float] = Field(
        None,
        description="The compressibility of the oil for this test step.  Compressibility is a measure of how much a substance can be compressed under pressure.",
        title="Oil Compressibility",
    )
    OilViscosity: Optional[float] = Field(
        None,
        description="The dynamic viscosity of the oil for this test step.",
        title="Oil Viscosity",
    )
    TotalVolume: Optional[float] = Field(
        None, description="The total volume for this test step.", title="TotalVolume"
    )
    RelativeVolumeRatio: Optional[float] = Field(
        None,
        description="The measured relative volume ratio = measured volume/volume at Psat.",
        title="Relative Volume Ratio",
    )
    GasDensity: Optional[float] = Field(
        None,
        description="The density of the gas for this test step.",
        title="Gas Density",
    )
    GasZFactor: Optional[float] = Field(
        None,
        description="The Z factor of the gas for this test step estimated for quality assurance of the laboratory data.",
        title="Gas Z Factor",
    )
    GasCompressibility: Optional[float] = Field(
        None,
        description="The compressibility of the gas for this test step.",
        title="Gas Compressibility",
    )
    GasViscosity: Optional[float] = Field(
        None,
        description="The viscosity of the gas phase at this test step.",
        title="Gas Viscosity",
    )
    YFunction: Optional[float] = Field(
        None,
        description="The Y-Function acts as a consistency check for CCE experiments of black oil.",
        title="Y Function",
    )
    SampleTestConditionID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-SampleTestCondition:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="Identifies the testing condition of the sample fluid, e.g. InitialReservoir, CurrentReservoir, StockTank, InitialSaturation.",
        title="Sample Test Condition ID",
    )
    PhasesPresent: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-FluidPhasesPresent:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="Identifies the phases of fluid present in the sample, e.g. SeparatorLiquid, FlashedOil, OilWithMud, Gas, ReservoirFluid (references FluidPhasesPresent).",
        title="Phases Present",
    )
    IsothermalFluidCompressibilityAverage: Optional[float] = Field(
        None,
        description="The compressibility of the fluid based on two discrete pressure points.",
        title="Isothermal Fluid Compressibility Average",
    )
    IsothermalFluidCompressibilityInstantaneous: Optional[float] = Field(
        None,
        description="Instantaneous Compressibility is the fluid compressibility at one pressure point calculated using the continuous nature of pressure-volume relation.",
        title="Isothermal Fluid Compressibility Instantaneous",
    )
    VaporComposition: Optional[List[VaporCompositionItem]] = Field(
        None,
        description="Array object capturing the composition of the vapor component of the sample at this test step.",
        title="Vapor Composition",
    )
    LiquidComposition: Optional[List[LiquidCompositionItem]] = Field(
        None,
        description="Array object capturing the composition of the liquid component of the sample at this test step.",
        title="Liquid Composition",
    )
    Remarks: Optional[List[Remark]] = Field(
        None,
        description="Array object capturing remarks or additional information for this test step.  Remarks for the analysis as a whole should be captured in the associated SamplesAnalysis work product component.",
        title="Remarks",
    )


class ConstantCompositionExpansionModel100(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    SamplesAnalysisID: constr(
        regex=r"^[\w\-\.]+:work-product-component\-\-SamplesAnalysis:[\w\-\.\:\%]+:[0-9]*$"
    ) = Field(
        ...,
        description="The OSDU Identifier for this SamplesAnalysis.",
        title="Samples Analysis ID",
    )
    SampleID: constr(
        regex=r"^[\w\-\.]+:master-data\-\-Sample:[\w\-\.\:\%]+:[0-9]*$"
    ) = Field(
        ...,
        description="The OSDU Identifier for the Sample associated with this analysis.",
        title="Sample ID",
    )
    Meta: List[Union[Meta, Meta1, Meta2, Meta3]] = Field(
        ..., description="Object", example="", title="Meta"
    )
    TestNumber: Optional[str] = Field(
        None,
        description="A number for this test for purposes of e.g., tracking lab sequence.",
        title="Test Number",
    )
    TestTemperature: Optional[float] = Field(
        None, description="The temperature of this test.", title="Test Temperature"
    )
    SaturationPressure: Optional[float] = Field(
        None,
        description="The saturation (or bubble point) pressure measured in this test.",
        title="Saturation Pressure",
    )
    ReservoirPressure: Optional[float] = Field(
        None,
        description="The pressure conditions of the reservoir where the sample was collected.",
        title="Reservoir Pressure",
    )
    TestSteps: Optional[List[TestStep]] = Field(
        None,
        description="An array object capturing the CCE test steps.",
        title="Test Steps",
    )
