#  Copyright 2023 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  cvd_data_schema.json
#   timestamp: 2024-09-11T19:19:38+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import Extra, confloat, constr

from app.models.config import RafsBaseModel


class StepPressure(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class GasDensity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class GasMoleWeight(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class GasViscosity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[confloat(ge=0.0)] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class GasFVF(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[confloat(ge=0.0)] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class VaporProperty(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    StepNumber: Optional[str] = None
    StepPressure: Optional[StepPressure] = None
    GasDensity: Optional[GasDensity] = None
    GasPhaseZFactor: Optional[float] = None
    TwoPhaseZFactor: Optional[float] = None
    GasMoleWeight: Optional[GasMoleWeight] = None
    GasViscosity: Optional[GasViscosity] = None
    GasFVF: Optional[GasFVF] = None
    Remarks: Optional[str] = None


class MolesDisplaced(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class ReservoirFluidDisplaced(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class ReservoirLiquidVolume(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class SaturationLiquidVolume(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class AbsoluteLiquidVolume(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class LiquidProperty(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    StepNumber: Optional[str] = None
    StepPressure: Optional[StepPressure] = None
    MolesDisplaced: Optional[MolesDisplaced] = None
    ReservoirFluidDisplaced: Optional[ReservoirFluidDisplaced] = None
    ReservoirLiquidVolume: Optional[ReservoirLiquidVolume] = None
    SaturationLiquidVolume: Optional[SaturationLiquidVolume] = None
    AbsoluteLiquidVolume: Optional[AbsoluteLiquidVolume] = None
    Remarks: Optional[str] = None


class RelativeMoleWeight(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class LiquidFraction(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class FluidCompositionItem(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    ComponentName: Optional[str] = None
    StepPressure: Optional[StepPressure] = None
    RelativeMoleWeight: Optional[RelativeMoleWeight] = None
    LiquidFraction: Optional[LiquidFraction] = None


class MoleWeight(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class ComponentMoleWeightItem(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    ComponentName: Optional[str] = None
    MoleWeight: Optional[MoleWeight] = None
    Remarks: Optional[str] = None


class CalculatedTotalProperty(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    StepNumber: Optional[float] = None
    StepPressure: Optional[StepPressure] = None
    MoleWeight: Optional[MoleWeight] = None
    GasGravity: Optional[float] = None
    ZFactor: Optional[float] = None
    ComponentMoleWeight: Optional[List[ComponentMoleWeightItem]] = None


class CvdDataSchema(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    SamplesAnalysisID: constr(
        regex=r"^[\w\-\.]+:work-product-component\-\-SamplesAnalysis:[\w\-\.\:\%]+:[0-9]*$"
    )
    SampleID: constr(regex=r"^[\w\-\.]+:master-data\-\-Sample:[\w\-\.\:\%]+:[0-9]*$")
    TestNumber: Optional[str] = None
    VaporProperties: Optional[List[VaporProperty]] = None
    LiquidProperties: Optional[List[LiquidProperty]] = None
    FluidComposition: Optional[List[FluidCompositionItem]] = None
    CalculatedTotalProperties: Optional[List[CalculatedTotalProperty]] = None
