#  Copyright 2023 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  diff_lib_data_schema.json
#   timestamp: 2024-09-11T19:19:39+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import Extra, constr

from app.models.config import RafsBaseModel


class TestTemperature(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class ResidualOilDensity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class ResidualAPIGravity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class SaturationPressure(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class ReservoirPressure(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class StepPressure(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class StepTemperature(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class OilDensity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class OilFormationVolumeFactor(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class OilCompressibility(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class OilViscosity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class GasMolecularWeight(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class GasGravity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class GasDensity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class GasFormationVolumeFactor(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class GasViscosity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class TotalFormationVolumeFactor(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class SolutionGasOilRatioMeasured(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class SolutionGasOilRatioCorrected(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class CumulativeStockTankGasOilRatio(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class OilFormationVolumeFactorCorrected(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class DifferentialLiberationTestStep(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    StepNumber: Optional[str] = None
    StepPressure: Optional[StepPressure] = None
    StepTemperature: Optional[StepTemperature] = None
    OilDensity: Optional[OilDensity] = None
    OilFormationVolumeFactor: Optional[OilFormationVolumeFactor] = None
    OilCompressibility: Optional[OilCompressibility] = None
    OilViscosity: Optional[OilViscosity] = None
    GasMolecularWeight: Optional[GasMolecularWeight] = None
    GasGravity: Optional[GasGravity] = None
    GasDensity: Optional[GasDensity] = None
    GasFormationVolumeFactor: Optional[GasFormationVolumeFactor] = None
    GasZFactor: Optional[float] = None
    GasViscosity: Optional[GasViscosity] = None
    TotalFormationVolumeFactor: Optional[TotalFormationVolumeFactor] = None
    SolutionGasOilRatioMeasured: Optional[SolutionGasOilRatioMeasured] = None
    SolutionGasOilRatioCorrected: Optional[SolutionGasOilRatioCorrected] = None
    CumulativeStockTankGasOilRatio: Optional[CumulativeStockTankGasOilRatio] = None
    OilFormationVolumeFactorCorrected: Optional[
        OilFormationVolumeFactorCorrected
    ] = None
    ResidualAPIGravity: Optional[ResidualAPIGravity] = None
    FluidConditions: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-SampleTestCondition:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None
    PhasesPresent: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-FluidPhasesPresent:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class RelativeMolarWeight(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class VaporCompositionItem(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    ComponentFormula: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-SampleCompositionComponent:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None
    ComponentName: Optional[str] = None
    RelativeMolarWeight: Optional[RelativeMolarWeight] = None


class VaporCompositionalAnalysi(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    StepNumber: Optional[str] = None
    StepPressure: Optional[StepPressure] = None
    StepTemperature: Optional[StepTemperature] = None
    GasGravity: Optional[GasGravity] = None
    Remark: Optional[str] = None
    VaporComposition: Optional[List[VaporCompositionItem]] = None


class FlashedLiquidRelativeMolarWeight(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class FlashedLiquidRelativeMass(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class FlashedGasRelativeMolarWeight(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class LiquidCompositionalAnalysi(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    ComponentFormula: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-SampleCompositionComponent:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None
    ComponentName: Optional[str] = None
    FlashedLiquidRelativeMolarWeight: Optional[FlashedLiquidRelativeMolarWeight] = None
    FlashedLiquidRelativeMass: Optional[FlashedLiquidRelativeMass] = None
    FlashedGasRelativeMolarWeight: Optional[FlashedGasRelativeMolarWeight] = None


class AvgMoleWeight(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class ResidueDensity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class ResidueAPI(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class FlashedLiquidDensity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class LiquidCalculatedProperty(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    ComponentFormula: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-SampleCompositionComponent:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None
    FlashedLiquidRelativeMolarWeight: Optional[FlashedLiquidRelativeMolarWeight] = None
    FlashedLiquidRelativeMass: Optional[FlashedLiquidRelativeMass] = None
    FlashedLiquidDensity: Optional[FlashedLiquidDensity] = None


class CalculatedProperties(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    AvgMoleWeight: Optional[AvgMoleWeight] = None
    ResidueDensity: Optional[ResidueDensity] = None
    ResidueAPI: Optional[ResidueAPI] = None
    Remark: Optional[str] = None
    LiquidCalculatedProperties: Optional[List[LiquidCalculatedProperty]] = None


class DiffLibDataSchema(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    SamplesAnalysisID: constr(
        regex=r"^[\w\-\.]+:work-product-component\-\-SamplesAnalysis:[\w\-\.\:\%]+:[0-9]*$"
    )
    SampleID: constr(regex=r"^[\w\-\.]+:master-data\-\-Sample:[\w\-\.\:\%]+:[0-9]*$")
    TestNumber: Optional[str] = None
    TestTemperature: Optional[TestTemperature] = None
    ResidualOilDensity: Optional[ResidualOilDensity] = None
    ResidualAPIGravity: Optional[ResidualAPIGravity] = None
    SaturationPressure: Optional[SaturationPressure] = None
    ReservoirPressure: Optional[ReservoirPressure] = None
    TestName: Optional[str] = None
    DifferentialLiberationTestSteps: Optional[
        List[DifferentialLiberationTestStep]
    ] = None
    VaporCompositionalAnalysis: Optional[List[VaporCompositionalAnalysi]] = None
    LiquidCompositionalAnalysis: Optional[List[LiquidCompositionalAnalysi]] = None
    CalculatedProperties: Optional[CalculatedProperties] = None
