#  Copyright 2024 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  ElectricalPropertiesDataSchema.1.0.0.json
#   timestamp: 2024-12-18T16:39:54+00:00

from __future__ import annotations

from app.models.config import RafsBaseModel

from typing import List, Optional

from pydantic import Extra, Field, constr


class TestStep(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    StepNumber: Optional[float] = Field(
        None,
        description="Internal step number which identifies the sequence of steps in this analysis.",
        title="Step Number",
    )
    IsPressureIncreasing: Optional[bool] = Field(
        None,
        description="Identifies whether the pressure is increasing or decreasing during this test step.  A value of True indicates an increasing pressure cycle.  False indicates a decreasing pressure cycle.",
        title="Is Pressure Increasing",
    )
    WaterSaturationOverResistivityIndex: Optional[float] = Field(
        None,
        description="The relationship between water saturation and resistivity index, used to interpret fluid saturations in the rock.",
        title="Water Saturation Over Resistivity Index",
    )
    BrineSaturation: Optional[float] = Field(
        None,
        description="The fraction of pore space in the rock that is filled with brine, a key input for water saturation models.",
        title="Brine Saturation",
    )
    ResistivityIndex: Optional[float] = Field(
        None,
        description="The index of resistivity used to relate resistivity measurements to water saturation in the sample.",
        title="Resistivity Index",
    )
    AdjustedResistivityIndex: Optional[float] = Field(
        None,
        description="The resistivity index value adjusted or corrected for specific conditions.",
        title="Adjusted Resistivity Index",
    )
    CapillaryPressure: Optional[float] = Field(
        None,
        description="Reported capillary pressure, if provided.",
        title="Capillary Pressure",
    )
    SaturationExponent: Optional[float] = Field(
        None,
        description="A factor describing the relationship between water saturation and resistivity, crucial for interpreting reservoir fluid saturation.",
        title="Saturation Exponent",
    )
    AdjustedSaturationExponent: Optional[float] = Field(
        None,
        description="A modified value of the saturation exponent, accounting for experimental conditions or measurement adjustments.",
        title="Adjusted Saturation Exponent",
    )
    FormationResistivityFactor: Optional[float] = Field(
        None,
        description="The ratio of the resistivity of the rock fully saturated with brine to the resistivity of the brine itself, used in determining water saturation. Also called FRF.",
        title="Formation Resistivity Factor",
    )
    NetConfiningStress: Optional[float] = Field(
        None,
        description="The pressure exerted on a sample from its environment, minus the pore pressure within the sample",
        title="Net Confining Stress",
    )
    Porosity: Optional[float] = Field(
        None,
        description="The amount of pore space relative to the volume of a sample.",
        title="Porosity",
    )
    PorosityFractionOfOriginalAmbient: Optional[float] = Field(
        None,
        description="The porosity of the sample at this test step as a fraction of the original porosity at ambient conditions.",
        title="Porosity Fraction Of Original Ambient",
    )
    PorosityFractionOfOriginalStandard: Optional[float] = Field(
        None,
        description="The porosity of the sample at this test step as a fraction of the original porosity at standard conditions.",
        title="Porosity Fraction Of Original Standard",
    )
    BrinePermeability: Optional[float] = Field(
        None,
        description="Quantifies the ability for brine to flow through a sample.",
        title="Brine Permeability",
    )
    BrinePermeabilityFractionOfOriginal: Optional[float] = Field(
        None,
        description="The permeability of the sample to brine at this test step as a fraction of the original permeability.",
        title="Brine Permeability Fraction Of Original",
    )


class ElectricalPropertiesModel100(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    SamplesAnalysisID: constr(
        regex=r"^[\w\-\.]+:work-product-component\-\-SamplesAnalysis:[\w\-\.\:\%]+:[0-9]*$"
    ) = Field(
        ...,
        description="OSDU Identifier for this SamplesAnalysis",
        title="Samples Analysis ID",
    )
    SampleID: constr(
        regex=r"^[\w\-\.]+:master-data\-\-Sample:[\w\-\.\:\%]+:[0-9]*$"
    ) = Field(
        ...,
        description="OSDU Identifier for the Sample associated with this analysis",
        title="Sample ID",
    )
    BrineConcentration: Optional[float] = Field(
        None,
        description="The salinity level of the brine used in the test, sometimes represented as CoCw or the Concentration of Conductive Water), affecting the rock's electrical resistivity properties.",
        title="Brine Concentration",
    )
    FormationResistivityFactor: Optional[float] = Field(
        None,
        description="The ratio of the resistivity of the rock fully saturated with brine to the resistivity of the brine itself, used in determining water saturation. Also called FRF.",
        title="Formation Resistivity Factor",
    )
    AdjustedFormationResistivityFactor: Optional[float] = Field(
        None,
        description="A modified value of the formation resistivity factor adjusted for specific experimental conditions or data corrections.",
        title="Adjusted Formation Resistivity Factor",
    )
    CementationExponent: Optional[float] = Field(
        None,
        description="A parameter in Archie’s law representing the rock’s pore structure and its influence on resistivity, affecting saturation calculations.",
        title="Cementation Exponent",
    )
    AdjustedCementationExponent: Optional[float] = Field(
        None,
        description="A modified value of the cementation exponent, accounting for specific experimental conditions or data corrections.",
        title="Adjusted Cementation Exponent",
    )
    AverageSaturationExponent: Optional[float] = Field(
        None,
        description="A factor describing the relationship between water saturation and resistivity, crucial for interpreting reservoir fluid saturation.",
        title="Average Saturation Exponent",
    )
    AdjustedAverageSaturationExponent: Optional[float] = Field(
        None,
        description="A modified value of the saturation exponent, accounting for experimental conditions or measurement adjustments.",
        title="Adjusted Average Saturation Exponent",
    )
    FormationFactorAtNetOverburdenPressure: Optional[float] = Field(
        None,
        description="The formation resistivity factor (FRF) measured under the net confining pressure that simulates in-situ reservoir conditions.",
        title="Formation Factor At Net Overburden Pressure",
    )
    AdjustedFormationFactorAtNetOverburdenPressure: Optional[float] = Field(
        None,
        description="The formation factor adjusted for experimental conditions under net overburden pressure.",
        title="Adjusted Formation Factor At Net Overburden Pressure",
    )
    NumberOfElectrodes: Optional[float] = Field(
        None,
        description="The number of electrodes used in the experimental setup to measure electrical properties in the sample.",
        title="Number Of Electrodes",
    )
    QuantityOfOilInTheVolume: Optional[float] = Field(
        None,
        description="The volume fraction of oil present in the rock sample during the electrical property measurement.",
        title="Quantity Of Oil In The Volume",
    )
    InjectionFluidID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-SampleInjectionFluidType:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="The type of fluid injected into a sample to displace other fluids during the experiment.",
        title="Injection Fluid Type ID",
    )
    DisplacedFluidTypeID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-DisplacedFluidType:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="The type of fluid being displaced from the rock sample during saturation or desaturation measurements.",
        title="Displaced Fluid Type ID",
    )
    SaturationProcessMethodID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-SaturationProcessMethod:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="The method used to saturate the rock sample with a particular fluid in the experiment.",
        title="Saturation Process Method ID",
    )
    DesaturationMethodID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-DesaturationMethod:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="The technique used to reduce the saturation of the rock sample, important for measuring electrical properties under varying saturations.",
        title="Desaturation Method ID",
    )
    BrineResistivity: Optional[float] = Field(
        None,
        description="The resistivity of the brine solution, which influences the resistivity index calculations.",
        title="Brine Resistivity",
    )
    Temperature: Optional[float] = Field(
        None,
        description="The temperature at which the electrical properties measurements are conducted, affecting fluid behavior and resistivity.",
        title="Temperature",
    )
    Frequency: Optional[float] = Field(
        None,
        description="The frequency of the electrical current used in the measurements, impacting the resistivity response of the rock.",
        title="Frequency",
    )
    FormationResistivity: Optional[float] = Field(
        None,
        description="This could also be Formation Conductivity.",
        title="Formation Resistivity",
    )
    FormationDiaelectricPermittivity: Optional[float] = Field(
        None,
        description="A measure of how easily the formation's materials (rock, fluid, and any pore spaces) can polarize in response to an applied electric field.",
        title="Formation Diaelectric Permittivity",
    )
    PorosityAtNetConfiningStress: Optional[float] = Field(
        None,
        description="The amount of pore space relative to the volume of a sample at net confining stress.",
        title="Porosity At Net Confining Stress",
    )
    CapillaryPressureAnalysisID: Optional[
        constr(
            regex=r"^[\w\-\.]+:work-product-component\-\-SamplesAnalysis:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="Identifier of the specific capillary pressure analysis related to this electrical properties analysis, if provided.",
        title="Capillary Pressure Analysis ID",
    )
    WOGnCycleNotationID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-WOGnCycleNotation:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="The WOGn notation description of the capillary pressure cycle.",
        title="Water Oil Gas Number ID",
    )
    TestSteps: Optional[List[TestStep]] = Field(
        None, description="The array of test data.", title="Test Steps"
    )
