#  Copyright 2023 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  mcm_data_schema.json
#   timestamp: 2023-11-16T00:14:37+00:00

from __future__ import annotations

from typing import Optional

from pydantic import Field, constr

from app.models.config import RafsBaseModel


class TestTemperature(RafsBaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class MolePctOfInjectedGas(RafsBaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class Model(RafsBaseModel):
    SamplesAnalysisID: constr(
        regex=r"^[\w\-\.]+:work-product-component\-\-SamplesAnalysis:[\w\-\.\:\%]+:[0-9]*$"
    )
    SampleID: constr(regex=r"^[\w\-\.]+:master-data\-\-Sample:[\w\-\.\:\%]+:[0-9]*$")
    TestNumber: Optional[str] = Field(
        None,
        description="A number for this test for purposes of e.g., tracking lab sequence.",
        title="Test Number",
    )
    TestTemperature: Optional[TestTemperature] = None
    TypeOfInjectedGas: Optional[str] = Field(
        None,
        description="Type of injected gas, example: Regular",
        title="Type of Injected Gas",
    )
    TypeOfMultiContactTest: Optional[str] = Field(
        None,
        description="Type of multiple contact test, example: Miscibility Test",
        title="Type of Multiple Contact Test",
    )
    MolePctOfInjectedGas: Optional[MolePctOfInjectedGas] = None
    GasSolventCompositionReference: Optional[str] = Field(
        None,
        description="Gas solvent composition reference, example: CO2",
        title="Gas Solvent Composition Reference",
    )
    MixRatio: Optional[float] = Field(
        None, description="Mix ratio, example: 365", title="Mix Ratio"
    )
