#  Copyright 2023 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  mercury_injection_analysis_data_schema.json
#   timestamp: 2023-08-10T14:42:07+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, constr


class Porosity(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class PoreVolume(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class BulkVolume(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class BrineDensityGradient(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class GasDensityGradient(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class AvgHydraulicRadius(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class InjectionSampleDatum(BaseModel):
    SampleID: Optional[str] = None
    Porosity: Optional[Porosity] = None
    PoreVolume: Optional[PoreVolume] = None
    BulkVolume: Optional[BulkVolume] = None
    BrineDensityGradient: Optional[BrineDensityGradient] = None
    GasDensityGradient: Optional[GasDensityGradient] = None
    AvgHydraulicRadius: Optional[AvgHydraulicRadius] = None
    FZI: Optional[float] = None
    SwansonParameter: Optional[float] = None


class LabAirBrineAngle(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class ReservoirAirBrineAngle(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class LabAirOilAngle(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class ReservoirAirOilAngle(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class LabOilBrineAngle(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class ReservoirOilBrineAngle(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class LabAirMercuryAngle(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class ReservoirAirMercuryAngle(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class IftCosineContactAngleItem(BaseModel):
    LabAirBrineAngle: Optional[LabAirBrineAngle] = None
    ReservoirAirBrineAngle: Optional[ReservoirAirBrineAngle] = None
    LabAirOilAngle: Optional[LabAirOilAngle] = None
    ReservoirAirOilAngle: Optional[ReservoirAirOilAngle] = None
    LabOilBrineAngle: Optional[LabOilBrineAngle] = None
    ReservoirOilBrineAngle: Optional[ReservoirOilBrineAngle] = None
    LabAirMercuryAngle: Optional[LabAirMercuryAngle] = None
    ReservoirAirMercuryAngle: Optional[ReservoirAirMercuryAngle] = None


class MercurySaturationFraction(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class EquivalentSaturationFraction(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class PoreThroatRadius(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class OnBottomPressure(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class GasBubblePressure(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class AnnulusBorePressure(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class HeightAboveFreeWater(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class InjectionTestStep(BaseModel):
    StepNumber: Optional[str] = None
    MercurySaturationFraction: Optional[MercurySaturationFraction] = None
    EquivalentSaturationFraction: Optional[EquivalentSaturationFraction] = None
    PoreThroatRadius: Optional[PoreThroatRadius] = None
    NormalizedPoreSizeDistributionFunction: Optional[float] = None
    OnBottomPressure: Optional[OnBottomPressure] = None
    GasBubblePressure: Optional[GasBubblePressure] = None
    AnnulusBorePressure: Optional[AnnulusBorePressure] = None
    HeightAboveFreeWater: Optional[HeightAboveFreeWater] = None
    NormalizedPermeabilityDistributionFunction: Optional[float] = None
    jFunction: Optional[float] = None


class Model(BaseModel):
    SamplesAnalysisID: str
    InjectionSampleData: Optional[List[InjectionSampleDatum]] = None
    IftCosineContactAngle: Optional[List[IftCosineContactAngleItem]] = None
    InjectionTestSteps: Optional[List[InjectionTestStep]] = None
