#  Copyright 2023 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  mss_data_schema.json
#   timestamp: 2023-12-06T00:34:43+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import Extra, constr

from app.models.config import RafsBaseModel


class ReservoirTemperature(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class SaturationPressure(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class ReservoirPressure(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class SaturatedOilFormationVolumeFactor(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class SaturatedOilDensity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class SeparatorTestGasOilRatio(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class OverallGasGravity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class StepPressure(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class StepTemperature(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class OilDensity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class GasGravity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class OilFormationVolumeFactor(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class SeparationVolumeFactor(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class GasFormationVolumeFactor(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class SaturationPressureCumulativeGasOilRatio(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class IndicatedPressureCumulativeGasOilRatio(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class GasZFactor(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class OilFormationVolumeFactorCorrected(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class GasOilRatio(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class GasOilRatioRsfb(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class MultiStageSeparatorTestDatum(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    StepNumber: Optional[str] = None
    StepPressure: Optional[StepPressure] = None
    StepTemperature: Optional[StepTemperature] = None
    OilDensity: Optional[OilDensity] = None
    GasGravity: Optional[GasGravity] = None
    OilFormationVolumeFactor: Optional[OilFormationVolumeFactor] = None
    SeparationVolumeFactor: Optional[SeparationVolumeFactor] = None
    GasFormationVolumeFactor: Optional[GasFormationVolumeFactor] = None
    SaturationPressureCumulativeGasOilRatio: Optional[
        SaturationPressureCumulativeGasOilRatio
    ] = None
    IndicatedPressureCumulativeGasOilRatio: Optional[
        IndicatedPressureCumulativeGasOilRatio
    ] = None
    GasZFactor: Optional[GasZFactor] = None
    OilFormationVolumeFactorCorrected: Optional[
        OilFormationVolumeFactorCorrected
    ] = None
    GasOilRatio: Optional[GasOilRatio] = None
    GasOilRatioRsfb: Optional[GasOilRatioRsfb] = None
    FluidCondition: Optional[str] = None
    PhasesPresent: Optional[str] = None


class RelativeMolarWeight(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class VaporCompositionItem(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    ComponentFormula: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-SampleCompositionComponent:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None
    ComponentName: Optional[str] = None
    RelativeMolarWeight: Optional[RelativeMolarWeight] = None


class VaporCompositionalAnalysi(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    StepNumber: Optional[str] = None
    StepPressure: Optional[StepPressure] = None
    StepTemperature: Optional[StepTemperature] = None
    VaporComposition: Optional[List[VaporCompositionItem]] = None


class FlashedLiquidRelativeMolarWeight(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class FlashedLiquidRelativeMass(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class FlashedGasRelativeMass(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class FlashedGasRelativeMolarWeight(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class LiquidCompositionalAnalysi(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    ComponentFormula: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-SampleCompositionComponent:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None
    ComponentName: Optional[str] = None
    FlashedLiquidRelativeMolarWeight: Optional[FlashedLiquidRelativeMolarWeight] = None
    FlashedLiquidRelativeMass: Optional[FlashedLiquidRelativeMass] = None
    FlashedGasRelativeMass: Optional[FlashedGasRelativeMass] = None
    FlashedGasRelativeMolarWeight: Optional[FlashedGasRelativeMolarWeight] = None


class AvgMoleWeight(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class ResidueDensity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class ResidueAPI(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class FlashedLiquidRelativeMolecularWeight(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class FlashedLiquidDensity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class LiquidCalculatedProperty(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    ComponentFormula: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-SampleCompositionComponent:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None
    FlashedLiquidRelativeMolarWeight: Optional[FlashedLiquidRelativeMolarWeight] = None
    FlashedLiquidRelativeMolecularWeight: Optional[
        FlashedLiquidRelativeMolecularWeight
    ] = None
    FlashedLiquidRelativeMass: Optional[FlashedLiquidRelativeMass] = None
    FlashedLiquidDensity: Optional[FlashedLiquidDensity] = None


class CalculatedProperties(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    AvgMoleWeight: Optional[AvgMoleWeight] = None
    ResidueDensity: Optional[ResidueDensity] = None
    ResidueAPI: Optional[ResidueAPI] = None
    Remark: Optional[str] = None
    LiquidCalculatedProperties: Optional[List[LiquidCalculatedProperty]] = None


class Model(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    SamplesAnalysisID: constr(
        regex=r"^[\w\-\.]+:work-product-component\-\-SamplesAnalysis:[\w\-\.\:\%]+:[0-9]*$"
    )
    SampleID: constr(regex=r"^[\w\-\.]+:master-data\-\-Sample:[\w\-\.\:\%]+:[0-9]*$")
    TestNumber: Optional[str] = None
    ReservoirTemperature: Optional[ReservoirTemperature] = None
    SaturationPressure: Optional[SaturationPressure] = None
    ReservoirPressure: Optional[ReservoirPressure] = None
    SaturatedOilFormationVolumeFactor: Optional[
        SaturatedOilFormationVolumeFactor
    ] = None
    SaturatedOilDensity: Optional[SaturatedOilDensity] = None
    SeparatorTestGasOilRatio: Optional[SeparatorTestGasOilRatio] = None
    OverallGasGravity: Optional[OverallGasGravity] = None
    Remark: Optional[str] = None
    MultiStageSeparatorTestData: Optional[List[MultiStageSeparatorTestDatum]] = None
    VaporCompositionalAnalysis: Optional[List[VaporCompositionalAnalysi]] = None
    LiquidCompositionalAnalysis: Optional[List[LiquidCompositionalAnalysi]] = None
    CalculatedProperties: Optional[CalculatedProperties] = None
