#  Copyright 2023 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  nmr_data_schema.json
#   timestamp: 2023-07-27T20:57:45+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, constr


class LiquidFilledPorosity(BaseModel):
    Value: Optional[str] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class T2LogMean(BaseModel):
    Value: Optional[str] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class FreshStateItem(BaseModel):
    LiquidFilledPorosity: Optional[LiquidFilledPorosity] = None
    T2LogMean: Optional[T2LogMean] = None


class Porosity(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class EffectivePorosity(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class T2LogMean1(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class FullBrineSaturationItem(BaseModel):
    Porosity: Optional[Porosity] = None
    EffectivePorosity: Optional[EffectivePorosity] = None
    T2LogMean: Optional[T2LogMean1] = None


class BVI(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class FFI(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class Swi(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class T2Cutoff(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class Saturation(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class T2(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = None


class IncrementalPorosityStep(BaseModel):
    StepNumber: Optional[str] = None
    Saturation: Optional[Saturation] = None
    T2: Optional[T2] = None
    Porosity: Optional[Porosity] = None


class PartialBrineSaturationItem(BaseModel):
    BVI: Optional[BVI] = None
    FFI: Optional[FFI] = None
    Swi: Optional[Swi] = None
    T2Cutoff: Optional[T2Cutoff] = None
    IncrementalPorositySteps: Optional[List[IncrementalPorosityStep]] = None


class Model(BaseModel):
    SamplesAnalysisID: constr(
        regex=r'^[\w\-\.]+:work-product-component\-\-SamplesAnalysis:[\w\-\.\:\%]+:[0-9]*$'
    )
    SampleID: Optional[
        constr(regex=r'^[\w\-\.]+:master-data\-\-Sample:[\w\-\.\:\%]+:[0-9]*$')
    ] = None
    FreshState: Optional[List[FreshStateItem]] = None
    FullBrineSaturation: Optional[List[FullBrineSaturationItem]] = None
    PartialBrineSaturation: Optional[List[PartialBrineSaturationItem]] = None
