#  Copyright 2023 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  api_v2/rca_data_schema.json
#   timestamp: 2023-11-01T20:45:25+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import Extra, confloat, constr

from app.models.config import RafsBaseModel


class SampleDepth(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: confloat(ge=0.0)
    UnitOfMeasure: constr(
        regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
    )


class Pressure(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None
    Type: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-PressureMeasurementType:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class Temperature(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class Conditions(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Pressure: Optional[Pressure] = None
    Temperature: Optional[Temperature] = None


class PermeabilityItem(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None
    Type: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-PermeabilityMeasurementType:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None
    Orientation: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-SampleOrientationType:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None
    Conditions: Optional[Conditions] = None


class PorosityItem(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None
    Type: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-PorosityMeasurementType:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None
    Orientation: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-SampleOrientationType:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None
    Conditions: Optional[Conditions] = None


class GrainDensityItem(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None
    Type: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-GrainDensityMeasurementType:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None
    Conditions: Optional[Conditions] = None


class SaturationItem(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None
    Type: Optional[str] = None
    Method: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-SaturationMethodType:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None
    Conditions: Optional[Conditions] = None


class Model(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    SamplesAnalysisID: constr(
        regex=r"^[\w\-\.]+:work-product-component\-\-SamplesAnalysis:[\w\-\.\:\%]+:[0-9]*$"
    )
    SampleID: constr(regex=r"^[\w\-\.]+:master-data\-\-Sample:[\w\-\.\:\%]+:[0-9]*$")
    CoringID: Optional[
        constr(regex=r"^[\w\-\.]+:master-data\-\-Coring:[\w\-\.\:\%]+:[0-9]*$")
    ] = None
    WellboreID: Optional[
        constr(regex=r"^[\w\-\.]+:master-data\-\-Wellbore:[\w\-\.\:\%]+:[0-9]*$")
    ] = None
    SampleNumber: str
    SampleType: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-RockSampleType:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None
    SampleDepth: SampleDepth
    Permeability: Optional[List[PermeabilityItem]] = None
    Porosity: Optional[List[PorosityItem]] = None
    GrainDensity: Optional[List[GrainDensityItem]] = None
    Saturation: Optional[List[SaturationItem]] = None
    LithologyDescription: Optional[str] = None
    Remarks: Optional[str] = None
