#  Copyright 2023 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  rock_compressibility_data_schema.json
#   timestamp: 2023-11-22T19:41:12+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import Extra, constr

from app.models.config import RafsBaseModel


class ConfiningStress(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class Porosity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class CompressibilityItem(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    CompressibilityType: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-CompressibilityMeasurementType:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class CompressibilityTestStep(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    StepNumber: Optional[int] = None
    ConfiningStress: Optional[ConfiningStress] = None
    Porosity: Optional[Porosity] = None
    Compressibility: Optional[List[CompressibilityItem]] = None


class Model(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    SamplesAnalysisID: constr(
        regex=r"^[\w\-\.]+:work-product-component\-\-SamplesAnalysis:[\w\-\.\:\%]+:[0-9]*$"
    )
    SampleID: constr(regex=r"^[\w\-\.]+:master-data\-\-Sample:[\w\-\.\:\%]+:[0-9]*$")
    CompressibilityTestSteps: Optional[List[CompressibilityTestStep]] = None
