#  Copyright 2023 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  vle_data_schema.json
#   timestamp: 2023-11-15T21:34:00+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import Extra, Field, constr

from app.models.config import RafsBaseModel


class TestTemperature(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class TestPressure(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class GasSolventAdded(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class MixtureVolume(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class MixtureGasSolventMoleFraction(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class MixtureGOR(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class MixturePsatTestTemperature(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class MixtureRelativeVolumeRelativeToPsat(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class VaporPhaseVolume(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class VaporPhaseViscosity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class VaporPhaseDensity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class LiquidPhaseVolume(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class LiquidPhaseDensity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class MoleFraction(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class MassFraction(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class VaporCompositionItem(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    ComponentName: Optional[str] = None
    MoleFraction: Optional[MoleFraction] = None
    MassFraction: Optional[MassFraction] = None


class LiquidCompositionItem(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    ComponentName: Optional[str] = None
    MoleFraction: Optional[MoleFraction] = None
    MassFraction: Optional[MassFraction] = None


class Model(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    SamplesAnalysisID: constr(
        regex=r"^[\w\-\.]+:work-product-component\-\-SamplesAnalysis:[\w\-\.\:\%]+:[0-9]*$"
    )
    SampleID: constr(regex=r"^[\w\-\.]+:master-data\-\-Sample:[\w\-\.\:\%]+:[0-9]*$")
    TestNumber: Optional[str] = None
    TestTemperature: Optional[TestTemperature] = Field(None, title="Test Temperature")
    TestPressure: Optional[TestPressure] = Field(None, title="Test Pressure")
    GasSolventAdded: Optional[GasSolventAdded] = Field(None, title="Gas Solvent Added")
    MixtureVolume: Optional[MixtureVolume] = Field(None, title="Mixture Volume")
    MixtureGasSolventMoleFraction: Optional[MixtureGasSolventMoleFraction] = Field(
        None, title="Mixture Gas Solvent Mole Fraction"
    )
    MixtureGOR: Optional[MixtureGOR] = Field(None, title="Mixture GOR")
    MixturePsatTestTemperature: Optional[MixturePsatTestTemperature] = Field(
        None, title="Mixture Psat Test Temperature"
    )
    MixtureRelativeVolumeRelativeToPsat: Optional[
        MixtureRelativeVolumeRelativeToPsat
    ] = Field(None, title="Mixture Relative Volume Relative To Psat")
    AtmosphericFlashTestReference: Optional[str] = None
    InjectedGasAdded: Optional[str] = None
    CumulativeGasAdded: Optional[str] = None
    VaporPhaseVolume: Optional[VaporPhaseVolume] = Field(
        None, title="Vapor Phase Volume"
    )
    VaporPhaseViscosity: Optional[VaporPhaseViscosity] = Field(
        None, title="Vapor Phase Viscosity"
    )
    VaporPhaseDensity: Optional[VaporPhaseDensity] = Field(
        None, title="Vapor Phase Density"
    )
    LiquidPhaseVolume: Optional[LiquidPhaseVolume] = Field(
        None, title="Liquid Phase Volume"
    )
    LiquidPhaseDensity: Optional[LiquidPhaseDensity] = Field(
        None, title="Liquid Phase Density"
    )
    VaporComposition: Optional[List[VaporCompositionItem]] = None
    VaporTransportTestReference: Optional[str] = None
    LiquidTransportTestReference: Optional[str] = None
    LiquidComposition: Optional[List[LiquidCompositionItem]] = None
    Remark: Optional[str] = None
