#  Copyright 2023 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  electrical_properties_data_schema.json
#   timestamp: 2023-07-17T13:09:55+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, constr


class BrineConcentration(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$")
    ] = None


class Model(BaseModel):
    SamplesAnalysisID: constr(
        regex=r"^[\w\-\.]+:work-product-component\-\-SamplesAnalysis:[\w\-\.\:\%]+:[0-9]*$"
    )
    SamplesID: constr(regex=r'^[\w\-\.]+:master-data-Samples:[\w\-\.\:\%]+:[0-9]*$')
    BrineConcentration: Optional[BrineConcentration] = None
    FormationFactor: Optional[float] = None
    AdjustedFormationFactor: Optional[float] = None
    CementationExponent: Optional[float] = None
    AdjustedCemetationExponent: Optional[float] = None
    SaturationExponent: Optional[float] = None
    AdjustedSaturationExponent: Optional[float] = None
