#  Copyright 2023 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  extraction_data_schema.json
#   timestamp: 2023-08-30T01:45:49+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field, constr


class WeightOfRockExtracted(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class WeightOfExtract(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class ExtractByRockWeight(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class ExtractOfTotalOrganicCarbon(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class Model(BaseModel):
    SamplesAnalysisID: constr(
        regex=r"^[\w\-\.]+:work-product-component\-\-SamplesAnalysis:[\w\-\.\:\%]+:[0-9]*$"
    )
    SampleID: constr(regex=r"^[\w\-\.]+:master-data\-\-Sample:[\w\-\.\:\%]+:[0-9]*$")
    WeightOfRockExtracted: Optional[WeightOfRockExtracted] = Field(
        None,
        description="weight of the rock sample that has been submitted for extraction. note - may be a fraction of the whole rock sample",
    )
    WeightOfExtract: Optional[WeightOfExtract] = Field(
        None, description="weight of fluid extract obtained from parent rock sample"
    )
    ExtractByRockWeight: Optional[ExtractByRockWeight] = Field(
        None,
        description="extract yield: weight of extract / weight of parent rock sample",
    )
    ExtractOfTotalOrganicCarbon: Optional[ExtractOfTotalOrganicCarbon] = Field(
        None, description="weight of extract as a percentage of Total Organic Carbon"
    )
