# generated by datamodel-codegen:
#   filename:  gcms_alkanes_data_schema.json
#   timestamp: 2023-08-15T21:44:27+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, constr


class RetentionTime(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class PeakItem(BaseModel):
    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None
    AreaHeightQualifier: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-CompoundsAreaHeight:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class SaturateCompound(BaseModel):
    CompoundCode: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-SaturateCompounds:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None
    RetentionTime: Optional[RetentionTime] = None
    Ion: Optional[str] = None
    Peak: Optional[List[PeakItem]] = None


class StdCompound(BaseModel):
    CompoundCode: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-SaturateCompounds:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None
    RetentionTime: Optional[RetentionTime] = None
    Ion: Optional[str] = None
    Peak: Optional[List[PeakItem]] = None


class Model(BaseModel):
    SamplesAnalysisID: constr(
        regex=r"^[\w\-\.]+:work-product-component\-\-SamplesAnalysis:[\w\-\.\:\%]+:[0-9]*$"
    )
    SampleID: constr(regex=r"^[\w\-\.]+:master-data\-\-Sample:[\w\-\.\:\%]+:[0-9]*$")
    SaturateCompounds: Optional[List[SaturateCompound]] = Field(
        None,
        description="The saturate hydrocarbon compounds fraction analysis",
        title="Saturate Compounds",
    )
    StdCompound: Optional[StdCompound] = Field(
        None, description="Compound added as internal standard"
    )
