variables:
  GC_SERVICE: rafs-ddms
  GC_INT_TEST_TYPE: python
  GC_SUPPORTED_PLATFORM: "linux/amd64"

gc-containerize-gitlab:
  variables:
    BUILD_PATH: "./Dockerfile"
    BUILD_ARGS: >
      --build-arg build_date="$CI_JOB_STARTED_AT"
      --build-arg commit_id=$CI_COMMIT_SHORT_SHA
      --build-arg commit_branch=$CI_COMMIT_BRANCH
      --build-arg user_id=65532

gc-containerize-gcr:
  variables:
    BUILD_PATH: "./Dockerfile"
    BUILD_ARGS: >
      --build-arg build_date="$CI_JOB_STARTED_AT"
      --build-arg commit_id=$CI_COMMIT_SHORT_SHA
      --build-arg commit_branch=$CI_COMMIT_BRANCH
      --build-arg user_id=65532

gc-osdutest:
  rules:
    - exists:
        - never/existing/file.txt

gc-test-python:
  script:
    - curl https://community.opengroup.org/api/v4/projects/1410/packages/generic/gc_auth_token/master/gc_auth_token -o gc_auth_token
    - chmod +x gc_auth_token
    - export GOOGLE_APPLICATION_CREDENTIALS=$GC_INTEGRATION_TESTER_SA_FILE
    - export GC_TOKEN=$(./gc_auth_token)
    - pip install -r requirements.txt
    - pip install -r requirements-tests.in
    - >-
      pytest -n auto tests/integration/tests
      --ddms-base-url ${DDMS_BASE_URL}
      --url-prefix ${URL_PREFIX}
      --partition ${DATA_PARTITION_ID}
      --bearer-token ${GC_TOKEN}
      --cloud-provider ${CLOUD_PROVIDER}
  # FIXME: should be deleted after int tests are configured correctly for GC implementation
  allow_failure: true

gc-dev2-osdutest:
  rules:
    - exists:
        - never/existing/file.txt

gc-dev2-test-python:
  script:
    - curl https://community.opengroup.org/api/v4/projects/1410/packages/generic/gc_auth_token/master/gc_auth_token -o gc_auth_token
    - chmod +x gc_auth_token
    - export GOOGLE_APPLICATION_CREDENTIALS=$GC_INTEGRATION_TESTER_SA_FILE
    - export GC_TOKEN=$(./gc_auth_token)
    - pip install -r requirements.txt
    - pip install -r requirements-tests.in
    - >-
      pytest -n auto tests/integration/tests
      --ddms-base-url ${DDMS_BASE_URL}
      --url-prefix ${URL_PREFIX}
      --partition ${DATA_PARTITION_ID}
      --bearer-token ${GC_TOKEN}
      --cloud-provider ${CLOUD_PROVIDER}
  # FIXME: should be deleted after int tests are configured correctly for GC implementation
  allow_failure: true
