{
 "title": "RAFS App metrics",
 "description": "Most relevant metrics from rafs ddms",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "RAM bytes consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_virtual_memory_bytes{instance=\"rafsddms:8080\"}[$__range])",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "App CPU Process time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"rafsddms:8080\"}[$__range])"
    }
   ]
  },
  {
   "title": "Http Request duration (sec) ALL",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=~\"/api/rafs-ddms/v1/coringreports|/api/rafs-ddms/v1/coringreports/\\\\{record_id\\\\}|/api/rafs-ddms/v1/coringreports/\\\\{record_id\\\\}/versions|/api/rafs-ddms/v1/coringreports/\\\\{record_id\\\\}/versions/\\\\{version\\\\}|/api/rafs-ddms/v1/rocksamples|/api/rafs-ddms/v1/rocksamples/\\\\{record_id\\\\}|/api/rafs-ddms/v1/rocksamples/\\\\{record_id\\\\}/versions|/api/rafs-ddms/v1/rocksamples/\\\\{record_id\\\\}/versions/\\\\{version\\\\}|/api/rafs-ddms/v1/rocksampleanalyses|/api/rafs-ddms/v1/rocksampleanalyses/\\\\{record_id\\\\}|/api/rafs-ddms/v1/rocksampleanalyses/\\\\{record_id\\\\}/rca/data|/api/rafs-ddms/v1/rocksampleanalyses/\\\\{record_id\\\\}/rca/source|/api/rafs-ddms/v1/rocksampleanalyses/\\\\{record_id\\\\}/versions|/api/rafs-ddms/v1/rocksampleanalyses/\\\\{record_id\\\\}/versions/\\\\{version\\\\}|/metrics\",job=\"rafs\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{handler=~\"/api/rafs-ddms/v1/coringreports|/api/rafs-ddms/v1/coringreports/\\\\{record_id\\\\}|/api/rafs-ddms/v1/coringreports/\\\\{record_id\\\\}/versions|/api/rafs-ddms/v1/coringreports/\\\\{record_id\\\\}/versions/\\\\{version\\\\}\",job=\"rafs\"}[$__rate_interval]))",
     "legendFormat": "coringreports"
    },
    {
     "expr": "sum(rate(http_requests_total{handler=~\"/api/rafs-ddms/v1/rocksampleanalyses|/api/rafs-ddms/v1/rocksampleanalyses/\\\\{record_id\\\\}|/api/rafs-ddms/v1/rocksampleanalyses/\\\\{record_id\\\\}/rca/data|/api/rafs-ddms/v1/rocksampleanalyses/\\\\{record_id\\\\}/rca/source|/api/rafs-ddms/v1/rocksampleanalyses/\\\\{record_id\\\\}/versions|/api/rafs-ddms/v1/rocksampleanalyses/\\\\{record_id\\\\}/versions/\\\\{version\\\\}\",job=\"rafs\"}[$__rate_interval]))",
     "legendFormat": "rocksampleanalyses"
    },
    {
     "expr": "sum(rate(http_requests_total{handler=~\"/api/rafs-ddms/v1/rocksamples|/api/rafs-ddms/v1/rocksamples/\\\\{record_id\\\\}|/api/rafs-ddms/v1/rocksamples/\\\\{record_id\\\\}/versions|/api/rafs-ddms/v1/rocksamples/\\\\{record_id\\\\}/versions/\\\\{version\\\\}\",job=\"rafs\"}[$__rate_interval]))",
     "legendFormat": "rocksamples"
    }
   ]
  },
  {
   "title": "HTTP Request Size Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_size_bytes_count{handler=~\"/api/rafs-ddms/v1/coringreports|/api/rafs-ddms/v1/coringreports/\\\\{record_id\\\\}|/api/rafs-ddms/v1/coringreports/\\\\{record_id\\\\}/versions|/api/rafs-ddms/v1/coringreports/\\\\{record_id\\\\}/versions/\\\\{version\\\\}\"}[$__rate_interval]))",
     "legendFormat": "/coringreports"
    },
    {
     "expr": "sum(rate(http_request_size_bytes_count{handler=~\"/api/rafs-ddms/v1/rocksampleanalyses|/api/rafs-ddms/v1/rocksampleanalyses/\\\\{record_id\\\\}|/api/rafs-ddms/v1/rocksampleanalyses/\\\\{record_id\\\\}/rca/data|/api/rafs-ddms/v1/rocksampleanalyses/\\\\{record_id\\\\}/rca/source|/api/rafs-ddms/v1/rocksampleanalyses/\\\\{record_id\\\\}/versions|/api/rafs-ddms/v1/rocksampleanalyses/\\\\{record_id\\\\}/versions/\\\\{version\\\\}\"}[$__rate_interval]))",
     "legendFormat": "/rocksampleanalyses"
    },
    {
     "expr": "sum(rate(http_request_size_bytes_count{handler=~\"/api/rafs-ddms/v1/rocksamples|/api/rafs-ddms/v1/rocksamples/\\\\{record_id\\\\}|/api/rafs-ddms/v1/rocksamples/\\\\{record_id\\\\}/versions|/api/rafs-ddms/v1/rocksamples/\\\\{record_id\\\\}/versions/\\\\{version\\\\}\"}[$__rate_interval]))",
     "legendFormat": "/rocksamples"
    }
   ]
  },
  {
   "title": "Request highr sec (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "rate(http_request_duration_highr_seconds_count{job=\"rafs\"}[$__rate_interval])",
     "legendFormat": "highr_seconds_count"
    },
    {
     "expr": "rate(http_request_duration_highr_seconds_sum{job=\"rafs\"}[$__rate_interval])",
     "legendFormat": "highr_seconds_sum"
    }
   ]
  },
  {
   "title": "Http Status",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({job=\"rafs\",status=\"4xx\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum({job=\"rafs\",status=\"2xx\"})"
    },
    {
     "expr": "sum({job=\"rafs\",status=\"5xx\"})"
    }
   ]
  }
 ]
}