{
 "title": "RAFS FastAPI Observability",
 "description": "Telemetry FastAPI application with three pillars of observability: Traces (Tempo), Metrics (Prometheus)",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Fast Api Endpoint",
    "query": {
     "query": "label_values(http_requests_total{}, handler)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{handler=\"$app_name\"})"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method) (http_requests_total{handler=\"$app_name\"})",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{handler=\"$app_name\"} / http_request_duration_seconds_count{handler=\"$app_name\"}",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Max request ms",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(http_request_duration_seconds_sum{job=\"rafs\",handler=\"$app_name\"})"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) (http_requests_total{handler=\"$app_name\", status=~\"2.*\"}) / sum by(handler) (http_requests_total{handler=\"$app_name\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percent of 4xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) (http_requests_total{handler=\"$app_name\", status=~\"4.*\"}) / sum by(handler) (http_requests_total{handler=\"$app_name\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(http_request_duration_seconds_bucket{handler=\"$app_name\"}[1m])) by(handler, le))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"$app_name\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}