#  Copyright 2023 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  api/schema-service/v1/schema/osdu:wks:master-data--GenericFacility:1.0.0
#   timestamp: 2023-12-12T16:50:26+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field, constr


class Field0(BaseModel):
    FacilitySpecificationText: Optional[str] = Field(
        None, description="The actual text value of the parameter."
    )
    FacilitySpecificationDateTime: Optional[datetime] = Field(
        None, description="The actual date and time value of the parameter."
    )
    FacilitySpecificationIndicator: Optional[bool] = Field(
        None, description="The actual indicator value of the parameter."
    )
    TerminationDateTime: Optional[datetime] = Field(
        None,
        description="The date and time at which the facility specification instance is no longer in effect.",
    )
    EffectiveDateTime: Optional[datetime] = Field(
        None,
        description="The date and time at which the facility specification instance becomes effective.",
    )
    UnitOfMeasureID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(
        None,
        description="The unit for the quantity parameter, like metre (m in SI units system) for quantity Length.",
    )
    FacilitySpecificationQuantity: Optional[float] = Field(
        None, description="The value for the specified parameter type."
    )
    ParameterTypeID: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-ParameterType:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = Field(None, description="Parameter type of property or characteristic.")
