global:
  scrape_interval: 10s # This should be raised to 30s in production envs
  scrape_timeout: 10s

scrape_configs:
  - job_name: rafs
    metrics_path: /api/rafs-ddms/v1/metrics
    static_configs:
      - targets:
          - 'rafsddms:8080'
  # Commenting out to have cleaner rafs metrics
  # - job_name: prometheus
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets:
  #         - 'prometheus:9090'
