#  Copyright 2024 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  black_oil_table_content_schema.json
#   timestamp: 2024-08-22T21:09:43+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import Extra, Field, constr

from app.models.config import RafsBaseModel


class Temperature(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class SaturationPressure(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class Salinity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class Pressure(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class SeparatorTrainItem(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Temperature: Optional[Temperature] = Field(
        None,
        description="The value and unit of measure of the temperature of the sample environment",
    )
    Pressure: Optional[Pressure] = Field(
        None,
        description="The value and unit of measure of the pressure of the sample environment",
    )


class SurfaceDensity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class SolutionGasOilRatio(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class FormationVolumeFactor(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class Viscosity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class Ga(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    SubTableIndex: Optional[str] = Field(
        None, description="Index number for this element of this subtable"
    )
    SurfaceDensity: Optional[SurfaceDensity] = None
    Pressure: Optional[Pressure] = None
    SolutionGasOilRatio: Optional[SolutionGasOilRatio] = None
    FormationVolumeFactor: Optional[FormationVolumeFactor] = Field(
        None,
        description="Ratio of the volume of gas at reservoir conditions of temperature and pressure to the volume at surface conditions",
    )
    Viscosity: Optional[Viscosity] = Field(
        None,
        description="A measure of the internal resistance of a fluid to flow against itself",
    )


class OilItem(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    SubTableIndex: Optional[str] = Field(
        None, description="Index number for this element of this subtable"
    )
    SurfaceDensity: Optional[SurfaceDensity] = None
    Pressure: Optional[Pressure] = None
    SolutionGasOilRatio: Optional[SolutionGasOilRatio] = None
    FormationVolumeFactor: Optional[FormationVolumeFactor] = Field(
        None,
        description="Ratio of the volume of gas at reservoir conditions of temperature and pressure to the volume at surface conditions",
    )
    Viscosity: Optional[Viscosity] = Field(
        None,
        description="A measure of the internal resistance of a fluid to flow against itself",
    )


class Compressibility(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class ViscosityCompressibility(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class WaterItem(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    SubTableIndex: Optional[str] = Field(
        None, description="Index number for this element of this subtable"
    )
    SurfaceDensity: Optional[SurfaceDensity] = None
    Pressure: Optional[Pressure] = None
    FormationVolumeFactor: Optional[FormationVolumeFactor] = Field(
        None,
        description="Ratio of the volume of gas at reservoir conditions of temperature and pressure to the volume at surface conditions",
    )
    Viscosity: Optional[Viscosity] = Field(
        None,
        description="A measure of the internal resistance of a fluid to flow against itself",
    )
    Compressibility: Optional[Compressibility] = Field(
        None, description="Volume change of a sample when pressure is applied"
    )
    ViscosityCompressibility: Optional[ViscosityCompressibility] = None


class Model(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    BlackOilTableID: constr(
        regex=r"^[\w\-\.]+:work-product-component\-\-BlackOilTable:[\w\-\.\:\%]+:[0-9]*$"
    ) = Field(..., description="Reference to the OSDU BlackOilTable WPC")
    UnitSystem: Optional[str] = None
    Temperature: Optional[Temperature] = Field(
        None,
        description="The value and unit of measure of the temperature of the sample environment",
    )
    SaturationPressure: Optional[SaturationPressure] = Field(
        None,
        description="The pressure at which a fluid within a sample begins to change from a liquid to a gaseous state",
    )
    Salinity: Optional[Salinity] = Field(
        None, description="Measure of dissolved salts in a sample"
    )
    SalinitySource: Optional[str] = None
    SeparatorTrain: Optional[List[SeparatorTrainItem]] = None
    Gas: Optional[List[Ga]] = None
    Oil: Optional[List[OilItem]] = None
    Water: Optional[List[WaterItem]] = None
