#  Copyright 2024 ExxonMobil Technology and Engineering Company
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# generated by datamodel-codegen:
#   filename:  mpfm_content_schema.json
#   timestamp: 2024-02-26T19:20:02+00:00

from __future__ import annotations

from datetime import datetime
from typing import List, Optional

from pydantic import Extra, Field, constr

from app.models.config import RafsBaseModel


class Temperature(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class Pressure(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class SeparatorTrainItem(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Temperature: Optional[Temperature] = None
    Pressure: Optional[Pressure] = None


class Salinity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class Calibration1(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None
    Type: Optional[str] = None


class Calibration(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Temperature: Optional[Temperature] = None
    Pressure: Optional[Pressure] = None
    Calibration: Optional[Calibration1] = None


class OilDensity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class GasDensity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class WaterDensity(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    Value: Optional[float] = None
    UnitOfMeasure: Optional[
        constr(
            regex=r"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$"
        )
    ] = None


class Model(RafsBaseModel):
    class Config:
        extra = Extra.forbid

    MeterType: Optional[str] = None
    SeparatorTrain: Optional[List[SeparatorTrainItem]] = None
    Salinity: Optional[Salinity] = None
    CalibrarionDate: Optional[datetime] = None
    Calibrations: Optional[List[Calibration]] = None
    MultiFlash: Optional[str] = Field(
        None,
        description="text contents of a multiflash file for this calibration, if any",
    )
    GasOilRatio: Optional[float] = None
    OilDensity: Optional[OilDensity] = None
    GasDensity: Optional[GasDensity] = None
    WaterDensity: Optional[WaterDensity] = None
